---
title: "aet v d"
author: "Janelle Christensen"
date: "2/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# 2/4/21
# Janele Christensen
# AET v. D climate future plots


# ------------------------
# attach packages
# ------------------------

library(tidyverse)
library(data.table)
library(here)
library(lubridate)
library(beepr)
library(httr)
library(directlabels)
library(ggrepel)
library(janitor)
```


```{r}
# -----------------------
# initialize variables
# -----------------------

site = "little_saddle_mtn" 

lat = 44.702 

lon = -110.018 

hist_start = 1980 

hist_end = 2010

future_center = 2040

future_timespan = 30 #how many years do you want to average your future data on?

future_start = future_center - (future_timespan / 2)

future_end = future_center + (future_timespan / 2)

aet_d_past_check <-  !file.exists(here::here("sites", 
                                  site, 
                                  "raw_data", 
                                  paste("lat_", lat, "_lon_", lon, sep = ""),
                                  "historical_aet_d.csv"))

# Threshold percentages for defining Climate futures. Default low/high:  0.25, 0.75
CFLow = 0.25     
CFHigh = 0.75
CFs = c("Warm Wet", "Hot Wet", "Central", "Warm Dry", "Hot Dry")

#suggest at least 30 yr chunk of time for both future and past
```

# Download Data

```{r, eval = aet_d_past_check}
# average of years in the past, average of years in the future

# -----------------------
# past data
# -----------------------

#initialize some variables to hold data 

holder <- NULL 

mydat <- NULL 

mydat2 <- NULL 

mydat3 <- NULL 

#This is the loop that runs across all the climate variables you want to download 

for(climvar in c("Deficit_monthly", "AET_monthly")){ 
  
  print(paste("downloading",climvar, "historical"))#this is a progress update as the loop runs 
  
  
  #the url uses two variable names for same variable in monthly download string like "PET_monthly" for long name and "pet" for short name 
  
  #the short name is sometimes a different case than the long variable name, so make it lowercase so that 
  
  #url string will work with the format of data stored on the cloud 
  
  varshort<-unlist(strsplit(climvar,"_m"));varshort 
  
  vshort<-varshort[[1]];vshort
  
  if(vshort=="Deficit"){#change case of short name from upper to lower case 
    
    vshort<-"deficit" 
    
  };vshort 
  
  
  if(vshort=="AET"){ 
    
    vshort<-"aet" 
    
  };vshort 
  
  for(yr in c(hist_start:hist_end)){# for each climate variable loop across the year.  allows users to select range if not interested in all data 
    
    #Specify URL where are stored on cloud 
    
    #single variable single year monthly time series with variable and year specified by user 
    
    leap <- lubridate::leap_year(yr) 
#leap years act differently with this monthly future data
#need to correct for that
    
    if(leap == TRUE){
      day <- 16
    } else {
      day <- 17
    }
    
    data_url<-paste("http://www.yellowstone.solutions/thredds/ncss/daily_or_monthly/v2_historical/gridmet_v_1_5_historical/V_1_5_",yr,"_gridmet_historical_",climvar,".nc4?var=",vshort,"&latitude=",lat,"&longitude=",lon,"&time_start=",yr,"-01-16T05%3A14%3A31.916Z&time_end=",yr,"-12-",day,"T00%3A34%3A14.059Z&accept=csv_file",sep ="") 
    
    
    holder <-data.frame(fread(data_url, 
                              verbose=FALSE, 
                              showProgress = FALSE,
    ))#temporary holder for subsets downloaded from cloud 
    
    mydat<-rbind(mydat, holder)#file that grows by adding each chunk downloaded from cloud 
    
  }#end loop across years 
  
  mydat2<-cbind(mydat2,mydat[,4])#append just the water balance data from each downloaded chunk 
  
  date <- mydat$time # date will download wrong
  
  mydat<-NULL#reset this variable so it can accodomate a new column name given the new water balance variable it's extracting at each loop cycle
  
  
}#end loop across climate variables 


mydat3<-cbind(date,holder[,2:3],mydat2)#join the data with meta data including date, lat, long 

colnames(mydat3)[]<-c("date", "lat","lon", "deficit_monthly", "aet_monthly") 

  divide.by.10 <- function(x, na.rm = FALSE) {
    x/10
  }
  
  mydat4 <- mydat3 %>% 
    mutate(lat = as.character(lat),
           lon = as.character(lon)) %>% 
    mutate_if(is.numeric, divide.by.10)
  
  write_csv(mydat4, here::here("sites",
                               site,
                               "raw_data",
                               paste("lat",lat,"lon",lon, sep = "_"),
                               "historical_aet_d.csv"))
  
beep(3)

```


```{r}

# -----------------------
# future data
# -----------------------

mydat7 <- NULL

climmodel <- c("inmcm4","NorESM1-M","MRI-CGCM3","MIROC5","IPSL-CM5A-LR","HadGEM2-CC365","GFDL-ESM2G","CanESM2","CSIRO-Mk3-6-0","CNRM-CM5","CCSM4", "BNU-ESM")# climate model names
for(m in climmodel){ #open climmodel
  #initialize some variables to hold data 
  
 
  
  #This is the loop that runs across all the climate variables you want to download 
  
  for(rcp in c("rcp45", "rcp85")){
    
    holder <- NULL 
    
    mydat <- NULL 
    
    mydat2 <- NULL
    
    for(climvar in c("Deficit_monthly", "AET_monthly")){ #open climvar
    
    
    print(paste("downloading", climvar, rcp, m))#this is a progress update as the loop runs 
    
    
    #the url uses two variable names for same variable in monthly download string like "PET_monthly" for long name and "pet" for short name 
    
    #the short name is sometimes a different case than the long variable name, so make it lowercase so that 
    
    #url string will work with the format of data stored on the cloud 
    
    varshort<-unlist(strsplit(climvar,"_m"));varshort 
    
    vshort<-varshort[[1]];vshort 
    
    if(vshort=="PET"){ 
      
      vshort<-"pet" 
      
    };vshort 
    
    
    if(vshort=="Deficit"){#change case of short name from upper to lower case 
      
      vshort<-"deficit" 
      
    };vshort 
    
    
    if(vshort=="AET"){ 
      
      vshort<-"aet" 
      
    };vshort 
    
    
    
    for(yr in c(future_start:future_end)){# for each climate variable loop across the year.  allows users to select range if not interested in all data 
      
      #single variable single year monthly time series with variable and year specified by user 
      
      leap <- lubridate::leap_year(yr) 
      if(leap == TRUE){
        day <- 16
      } else {
        day <- 17
      }
      
      data_url<- paste("http://www.yellowstone.solutions/thredds/ncss/daily_or_monthly/gcm/",rcp,"/",m,"/V_1_5_",yr,"_",m,"_",rcp, "_",climvar,".nc4?var=",vshort,"&latitude=",lat,"&longitude=",lon,"&time_start=",yr,"-01-16T05%3A14%3A31.916Z&time_end=",yr,"-12-",day,"T00%3A34%3A14.059Z&accept=csv_file",sep ="")

      
      holder <-data.frame(fread(data_url, 
                                verbose=FALSE, 
                                showProgress = FALSE,
      ))#temporary holder for subsets downloaded from cloud 
      
      colnames(holder) <- c("time", "latitude", "longitude", paste(climvar))
      
      mydat<-rbind(mydat, holder)#file that grows by adding each chunk downloaded from cloud 
      
      date <- mydat$time
      
    }#end loop across years 
    
    mydat2<-cbind(mydat2,mydat[,4])#append just the water balance data from each downloaded chunk 
    
    mydat<-NULL#reset this variable so it can accodomate a new column name given the new water balance variable it's extracting at each loop cycle 
    
  }#end loop across climate variables 
    
  if(rcp == "rcp45"){
    
    mydat3 <- NULL 
    
  mydat3<-cbind(date,holder[,2:3],mydat2) #join the data with metadat including date, lat, long 
  
  }# close if for rcp45 
    
if(rcp == "rcp85"){
      
      mydat4 <- NULL
      
      mydat4 <- cbind(date,holder[,2:3],mydat2) #join the data with metadat including date, lat, long 
      
    } #close if rcp85
    
  } #close rcp
  
  mydat5 <- cbind(mydat3,mydat4[,4:5]) #join the data with metadata including date, lat, long
  
  colnames(mydat5)[] <- c("date", "lat","lon","deficit_monthly_45", "aet_monthly_45", "deficit_monthly_85", "aet_monthly_85") 
  
  divide.by.10 <- function(x, na.rm = FALSE) {
    x/10
  }
  
  mydat6 <- mydat5 %>% 
    mutate(lat = as.character(lat),
           lon = as.character(lon)) %>% 
    mutate_if(is.numeric, divide.by.10) %>% 
    mutate(model = m)
  
  mydat7 <- rbind(mydat7, mydat6)
  
}# end loop across different climate projections

  write_csv(mydat7, here::here("sites", 
                               site, 
                               "raw_data", 
                               paste("lat",lat,"lon",lon, sep = "_"), 
                               "future_aet_d.csv")) #default is a space, sep = "" removes space
beep(1)

# here::here allows you to choose a folder in your working directory to save to
# here::here("folder I want to save to (this has to be made in your working directory before you save it)", "subfolder", "subfolder ( subfolders can be as numerous you want them to be, always separated by a commma)", "last thing in the list is the name of the object I'm saving")


```
```{r}


aet_d_past <- read_csv(here::here("sites",
                               site,
                               "raw_data",
                               paste("lat",lat,"lon",lon, sep = "_"),
                               "historical_aet_d.csv")) %>% 
  mutate(year = year(date)) %>% 
  mutate(time = "past",
         rcp = "past",
         model = "gridMET") %>% 
  group_by(year) %>% 
  summarize(deficit_past_total = unique(sum(deficit_monthly)),
         aet_past_total = unique(sum(aet_monthly)),
         time = unique(time),
         rcp = unique(rcp),
         model = unique(model)) %>% 
  summarize(deficit_past = mean(deficit_past_total),
            aet_past = mean(aet_past_total),
            time = unique(time),
            rcp = unique(rcp),
            model = unique(model))


RCPs <- as.character(c(45, 85))

d_future <- read_csv(here::here("sites", 
                               site, 
                               "raw_data", 
                               paste("lat",lat,"lon",lon, sep = "_"), 
                               "future_aet_d.csv")) %>% 
  mutate(year = year(date)) %>% 
  mutate(time = "future") %>% 
  select(!c(aet_monthly_45,aet_monthly_85)) %>% 
  pivot_longer(c(deficit_monthly_45, deficit_monthly_85),
               names_to = "rcp",
               values_to = "deficit") %>% 
  mutate(rcp = as.character(str_extract_all(rcp, RCPs))) %>% 
  mutate(rcp = case_when(.$rcp == "45" ~ "RCP 4.5",
                         TRUE ~ "RCP 8.5")) %>%
  group_by(time, model, rcp, year) %>%
  summarize(deficit_total = sum(deficit, na.rm = TRUE)) %>% 
  summarize(avg_deficit = mean(deficit_total, na.rm = TRUE),
            time = unique(time)) %>% 
  ungroup(time, model, rcp)


aet_future <- read_csv(here::here("sites", 
                               site, 
                               "raw_data", 
                               paste("lat",lat,"lon",lon, sep = "_"), 
                               "future_aet_d.csv")) %>% 
  select(!c(deficit_monthly_45,deficit_monthly_85)) %>% 
  mutate(year = year(date)) %>% 
  mutate(time = "future") %>%  
  pivot_longer(aet_monthly_45:aet_monthly_85,
               names_to = "rcp",
               values_to = "aet") %>% 
  mutate(rcp = as.character(str_extract_all(rcp, RCPs))) %>% 
  mutate(rcp = case_when(.$rcp == "45" ~ "RCP 4.5",
                         TRUE ~ "RCP 8.5")) %>% 
  group_by(time, model, rcp, year) %>% 
  summarize(aet_total = sum(aet, na.rm = TRUE)) %>% 
  summarize(avg_aet = mean(aet_total, na.rm = TRUE),
            time = unique(time)) %>% 
  ungroup(time, model, rcp)


aet_d_future <- aet_future %>% 
  inner_join(d_future)

aet_d <- aet_d_future %>% 
  full_join(aet_d_past) 

aet_d_difference <- aet_d  %>% 
  fill(aet_past, deficit_past, .direction = "up") %>% 
  mutate(aet_diff = avg_aet - aet_past,
         deficit_diff = avg_deficit - deficit_past) %>% 
  mutate(aet_percent_change = (((avg_aet - aet_past) / aet_past) * 100),
         deficit_percent_change = (((avg_deficit - deficit_past) / deficit_past) * 100)) %>% 
  mutate(model_rcp = paste(model, rcp)) 

#%>% # work to do something here with setting the quantiles like amber did in her data
#  mutate(climate_future = case_when())


ggplot(data = aet_d_difference, aes(x = deficit_diff, y = aet_diff)) +
  geom_point() +
  geom_label_repel(aes(label = model_rcp), max.overlaps = 24)

ggplot(data = aet_d_difference, aes(x = deficit_percent_change, y = aet_percent_change)) +
  geom_point() +
  geom_text_repel(aes(label = model_rcp))


```
```{r}
tvp <- c("Model,X_RCP45(in),Y_RCP45(F),X_RCP85(in),Y_RCP85(F)",
"bcc-csm1-1, 1.377, 4.372, 2.613, 5.725",
"bcc-csm1-1-m, 0.119, 3.444, 2.274, 5.280",
"BNU-ESM, 2.560, 4.565, 3.521, 6.656",
"CanESM2, 4.477, 5.512, 7.878, 7.251",
"CCSM4, 1.162, 4.375, 1.524, 5.782",
"CNRM-CM5, 2.028, 3.720, 3.962, 4.969",
"CSIRO-Mk3-6-0, -0.109, 5.491, 0.831, 6.252",
"GFDL-ESM2M, 1.856, 2.105, 0.670, 3.646",
"GFDL-ESM2G, 1.711, 3.985, 2.898, 4.292",
"HadGEM2-CC365, 2.071, 5.023, 0.876, 7.492",
"HadGEM2-ES365, 1.712, 5.435, 0.971, 7.535",
"inmcm4, 1.752, 2.257, 1.865, 4.373",
"IPSL-CM5A-LR, -0.152, 4.670, -0.287, 6.414",
"IPSL-CM5A-MR, 0.458, 5.401, 1.346, 7.286",
"IPSL-CM5B-LR, 1.160, 3.361, 1.330, 4.718",
"MIROC5, 3.345, 6.068, 5.369, 7.057",
"MIROC-ESM, 4.665, 6.684, 3.982, 8.286",
"MIROC-ESM-CHEM, 6.018, 6.599, 7.009, 8.647",
"MRI-CGCM3, 1.794, 1.606, 3.449, 2.843",
"NorESM1-M, 3.992, 4.821, 3.687, 6.276",
"CMIP5ModelMean, 2.100, 4.474, 2.788, 6.039")

tvp_df <- as.data.frame(data.table::fread(paste(tvp, collapse = "\n"))) %>% 
  clean_names()
```

t_v_p 
