---
title: "Single variable graphs"
author: "Janelle Christensen"
date: "6/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# ------------
# set variables for the data and code
# all of this should be changed before the code is run for a new site
# ------------
# 

climvar = "accumswe"

# site = "bandelier"

# lat = 35.75758546

# lon = -106.3054344

# model_bc = "inmcm4" # "best case"

# model_bc_rcp = "rcp45"

# model_wc = "NorESM1-M" # "worst case"

# model_wc_rcp = "rcp85"

site = "yellowstone"
# 
lat = 44.59644457

lon = -110.5471962

model_wc <- "IPSL-CM5A-LR"

model_wc_rcp <- "rcp85"

model_bc <- "MRI-CGCM3"

model_bc_rcp <- "rcp85"


# # model options: CCSM4, inmcm4, NorESM1-M, MRI-CGCM3, MIROC5, IPSL-CM5A-LR,  HadGEM2-CC365, GFDL-ESM2G, CanESM2, CSIRO-Mk3-6-0, CNRM-CM5, BNU-ESM

# RCP options: "rcp45", "rcp85" 

model_bc_rcp_name = if(model_bc_rcp == "rcp45"){
  paste("RCP 4.5")
} else {
  paste("RCP 8.5")
} #automatically makes a more "readable" version of the rcp for graph titles and such


model_wc_rcp_name = if(model_wc_rcp == "rcp45"){
  paste("RCP 4.5")
} else {
  paste("RCP 8.5")
} #automatically makes a more "readable" version of the rcp for graph titles and such

 past_data = "gridMET"
# 
# # past_data options: "gridMET", "Daymet"
# # if you want to use data that will work with the future models, gridMET is a better choice. It doesn't require adjusting for any biases
# 
 dry_year = 2011 # a particularly dry year, maybe with lots of fire activity? something for people to reference
# 
wet_year = 1997 # particulary wet year for people to reference


# -------------
# attach packages
# -------------

if (!require("pacman")) install.packages("pacman")
pacman::p_load(remotes, data.table, here, tidyverse, beepr, lubridate, directlabels, data.table, ggbeeswarm, gghalves, directlabels, ggrepel, splines, magrittr, janitor, ggalt, ggrepel, sp, sf) 
#pacman package installs packages required to run the script
#the p_load function is for the packages that are a part of CRAN

pacman::p_load_gh("earthlab/cft")

library(data.table) 
library(here)
#library(plyr) 
# be careful with this, it causes issues for dplyr::group_by
# I didn't try, but the internet says if you load it before tidyverse, that issue goes away
library(tidyverse)
library(beepr)
library(lubridate)
library(directlabels)
library(data.table)
library(ggbeeswarm)
library(gghalves)
library(directlabels)
library(splines)
library(magrittr)
library(janitor)
library(ggalt)
library(cft)
library(ggrepel)
library(sp)
library(sf)
```

```{r}

# -----------
# set global options
# -----------

#set theme for all graphs
theme_set(theme_classic() + #has the L shape around the graph
            theme(panel.grid = element_blank(), #removes grid lines
                  plot.title = element_text(size = 25), #title of plot text size
                  legend.text = element_text(size = 15), #legend inside text size
                  legend.title = element_text(size = 18), #legend title text size
                  axis.title.y = element_text(size = 15), #changes y axis lable text size
                  axis.title.x = element_blank(),#x axis text size
                  axis.text.x = element_text(size = 15), #changes x-axis text size
                  axis.text.y = element_text(size = 15), #changes y-axis text size
                  legend.position = "top"))  #location of legend

wrap_sentence <- function(string, width) {
  words <- unlist(strsplit(string, " "))
  fullsentence <- ""
  checklen <- ""
  for(i in 1:length(words)) {
    checklen <- paste(checklen, words[i])
    if(nchar(checklen)>(width+1)) {
      fullsentence <- paste0(fullsentence, "\n")
      checklen <- ""
    }
    fullsentence <- paste(fullsentence, words[i])
  }
  fullsentence <- sub("^\\s", "", fullsentence)
  fullsentence <- gsub("\n ", "\n", fullsentence)
  return(fullsentence)
}
#wrap_sentence function taken from https://stackoverflow.com/a/27734975/14061596


# ----------
# inmcm4, NorESM1-M downloaded wrong, don't use until updated (noted this 8-5-20)
# ----------

```

```{r}
# ------------
# DAILY DATA
# clean data for graphing
# ------------

# ------------
# daily future data
# ------------

future_day_1 <- read_csv(here::here("sites",
                                    site,
                                    paste(site,model_wc,model_wc_rcp, model_bc,model_bc_rcp, climvar, ".csv", sep = "_")),
                    na = c("-3276.7"))

date_fd <- future_day_1$date
# this is a work around
# want to remove data that has all zeroes conditionally based on site
# couldn't get data to work to only remove data that had a sum of zero unless removed all non-variable columns


future_day <- future_day_1 %>% 
  select(-lat, -lon, -date) %>%
  #select(which(!colSums(., na.rm = TRUE) < 2)) %>% # this removes variable that sum to 2 (i.e. accumswe in a hot climate)
  mutate(date = date_fd,
    year = lubridate::year(date), 
    month = lubridate::month(date,
                             label = TRUE,
                             abbr = TRUE),
    day = lubridate::day(date),
    doy = yday(date))


# ------------
# daily past
# ------------

past_day_1 <- read_csv(here::here("sites",
                                    site,
                                  paste("historical_", climvar, ".csv", sep = "")),
                           na = c("-3276.7")) 

date_pd <- past_day_1$date# this is a work around
# want to remove data that has all zeroes conditionally based on lat and lon
# couldn't get data to work to only remove data that had a sum of zero unless removed all non-variable columns

past_day <- past_day_1 %>% 
  select(-lat, -lon, -date)  %>%
  select(which(!colSums(., na.rm = TRUE) < 2)) %>% # this removes variables that sum to 2 (i.e. accumswe in a hot climate)
  mutate(date = date_pd,
         year = lubridate::year(date),
         month = lubridate::month(date,
                                  label = TRUE,
                                  abbr = TRUE),
         day = lubridate::day(date),
         doy = yday(date)) 
# %>% 
#   rename(deficit_daily = Deficit_daily) 


```

```{r}
# -------------
# Make site data into long format
# -------------

# -------------
# past data daily for summarizing by year
# -------------

annual_past <- past_day %>% 
  group_by(year) %>% 
  filter(!year == 2020) %>% 
  summarize(annual_accumswe = sum(accumswe_daily, na.rm = TRUE) 
            #annual_agdd = max(agdd_daily, na.rm = TRUE), 
            #put this back in when agdd is working
            )
# annual_soil_water = mean(soil_water_daily, na.rm = TRUE),
#             annual_runoff = sum(runoff_daily, na.rm = TRUE), 
#             annual_rain = sum(rain_daily, na.rm = TRUE),
#             annual_accumswe = max(accumswe_daily, na.rm = TRUE),
#             annual_pet = sum(pet_daily, na.rm = TRUE),
#annual_aet = sum(aet_daily, na.rm = TRUE)


# -------------
# long format future data daily
# -------------

# -------------
# worst case
# -------------

wc_annual_future <- future_day %>%
  select(accumswe_daily_wc, date:doy) %>% # soil_water_daily_wc:aet_daily_wc, selecting for variables for 8.5 only
  filter(!year == 2100) %>% 
  group_by(year) %>% 
    summarize(annual_accumswe_wc = sum(accumswe_daily_wc, na.rm = TRUE))

# annual_soil_water_wc = mean(soil_water_daily_wc, na.rm = TRUE),
#               annual_runoff_wc = sum(runoff_daily_wc, na.rm = TRUE),
#               annual_rain_wc = sum(rain_daily_wc, na.rm = TRUE),
#               annual_accumswe_wc = max(accumswe_daily_wc, na.rm = TRUE),
#               annual_pet_wc = sum(pet_daily_wc, na.rm = TRUE),
#               annual_deficit_wc = sum(deficit_daily_wc, na.rm = TRUE),
#               #annual_agdd_wc = max(agdd_daily_wc, na.rm = TRUE), 
#               #put this back in when agdd is working
#               annual_aet_wc = sum(aet_daily_wc, na.rm = TRUE)
    
#-------------
# best case
# ------------
  
bc_annual_future <- future_day %>% 
  select(accumswe_daily_bc, date:doy) %>% #soil_water_daily_bc:aet_daily_bc,selecting for 4.5 only
  filter(!year == 2100) %>% 
  group_by(year) %>% 
    summarize(annual_accumswe_bc = sum(accumswe_daily_bc, na.rm = TRUE))

# annual_soil_water_bc = mean(soil_water_daily_bc, na.rm = TRUE),
#               annual_runoff_bc = sum(runoff_daily_bc, na.rm = TRUE),
#               annual_rain_bc = sum(rain_daily_bc, na.rm = TRUE),
#               annual_accumswe_bc = max(accumswe_daily_bc, na.rm = TRUE),
#               annual_deficit_bc = sum(deficit_daily_bc, na.rm = TRUE),
#               annual_pet_bc = sum(pet_daily_bc, na.rm = TRUE),
#               #annual_agdd_bc = max(agdd_daily_bc, na.rm = TRUE),
#               #put this back in when agdd is working
#               annual_aet_bc = sum(aet_daily_bc, na.rm = TRUE)

# -----------
# make values into one df
# -----------

# -----------
# best case
# ----------

bc_annual_values <- annual_past %>%
  full_join(bc_annual_future) %>% 
  pivot_longer(`annual_accumswe`:`annual_accumswe_bc`,#`annual_soil_water`:`annual_aet_bc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "annual_value") %>% 
  na.omit(annual_values) %>% # new column name to store values
  mutate(decade = case_when(
    .$year %in% c(1980:1989) ~ "1980s",
    .$year %in% c(1990:1999) ~ "1990s",
    .$year %in% c(2000:2009) ~ "2000s",
    .$year %in% c(2010:2019) ~ "2010s",
    .$year %in% c(2020:2029) ~ "2020s",
    .$year %in% c(2030:2039) ~ "2030s",
    .$year %in% c(2040:2049) ~ "2040s",
    .$year %in% c(2050:2059) ~ "2050s",
    .$year %in% c(2060:2069) ~ "2060s",
    .$year %in% c(2070:2079) ~ "2070s",
    .$year %in% c(2080:2089) ~ "2080s",
    TRUE ~ "2090s"
  ))  %>%  mutate(variable = case_when(
    .$variable %in% c("annual_runoff", "annual_runoff_bc") ~ "Runoff",
    #.Svariable calls the variable, then it can be renamed
    .$variable %in% c("annual_agdd", "annual_agdd_bc") ~ "AGDD",
    .$variable %in% c("annual_soil_water", "annual_soil_water_bc") ~ "Soil Water",
    .$variable %in% c("annual_rain", "annual_rain_bc") ~ "Rain",
    .$variable %in% c("annual_accumswe", "annual_accumswe_bc") ~ "Accumulated SWE",
    .$variable %in% c("annual_pet", "annual_pet_bc") ~ "PET",
    .$variable %in% c("annual_deficit", "annual_deficit_bc") ~ "Deficit",
    TRUE ~ "AET" # last ifelse is just labeled as TRUE
  )) %>% 
  mutate(averages = case_when(
    .$year %in% c(1980:2019) ~ "annual_avg",
    TRUE ~ "annual_avg_bc"
  )) %>% 
  mutate(decades = case_when( #don't need individual decades for this data
    .$year %in% c(1980:2019) ~ "1980-2019",
    .$year %in% c(2020:2059) ~ "2020-2059",
    TRUE ~ "2060-2099")) #decades by 39 yr chunks



# ------------
# worst case
# ------------

wc_annual_values <- annual_past %>% 
  full_join(wc_annual_future) %>%
  pivot_longer(`annual_accumswe`:`annual_accumswe_wc`,#`annual_soil_water`:`annual_aet_wc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "annual_value") %>% 
  na.omit(annual_values) %>% # new column name to store values
  mutate(decade = case_when(
    .$year %in% c(1980:1989) ~ "1980s",
    .$year %in% c(1990:1999) ~ "1990s",
    .$year %in% c(2000:2009) ~ "2000s",
    .$year %in% c(2010:2019) ~ "2010s",
    .$year %in% c(2020:2029) ~ "2020s",
    .$year %in% c(2030:2039) ~ "2030s",
    .$year %in% c(2040:2049) ~ "2040s",
    .$year %in% c(2050:2059) ~ "2050s",
    .$year %in% c(2060:2069) ~ "2060s",
    .$year %in% c(2070:2079) ~ "2070s",
    .$year %in% c(2080:2089) ~ "2080s",
    TRUE ~ "2090s" #decade individually
  )) %>% 
  mutate(variable = case_when( #make names more readable
    .$variable %in% c("annual_runoff", "annual_runoff_wc") ~ "Runoff",
    #.$variable calls the variable, then it can be renamed
    .$variable %in% c("annual_agdd", "annual_agdd_wc") ~ "AGDD",
    .$variable %in% c("annual_soil_water", "annual_soil_water_wc") ~ "Soil Water",
    .$variable %in% c("annual_rain", "annual_rain_wc") ~ "Rain",
    .$variable %in% c("annual_accumswe", "annual_accumswe_wc") ~ "Accumulated SWE",
    .$variable %in% c("annual_pet", "annual_pet_wc") ~ "PET",
    .$variable %in% c("annual_deficit", "annual_deficit_wc") ~ "Deficit",
    TRUE ~ "AET" # last ifelse is just labeled as TRUE
  ))  %>% 
  mutate(averages = case_when(
    .$year %in% c(1980:2019) ~ "annual_avg",
    TRUE ~ "annual_avg_wc"
  )) %>% 
  mutate(decades = case_when( #don't need individual decades for this data
    .$year %in% c(1980:2019) ~ "1980-2019",
    .$year %in% c(2020:2059) ~ "2020-2059",
    TRUE ~ "2060-2099")) #decades by 39 yr chunks

# ---------------
# all together now!
# ---------------

annual_values <- bc_annual_values %>% 
  full_join(wc_annual_values) 


```

```{r}

## Data for graphs for 40 yr. period, shifts in timing of events

# --------
# clean data for 40 yr graphs
# graphs grouped by 40 yr chunks
# graphs then grouped by doy
# mean of doy taken, to be plotted on a single line that represents the mean of the doy for that 40 yr chunk
# --------

doy_avg_1980_2019 <-  past_day %>% 
  filter(year %in% c(1980:2019)) %>%
  pivot_longer(accumswe_daily,
    #`soil_water_daily`:`aet_daily`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>%  # new column name to store values) 
#for grouping by doy
  group_by(doy, variable) %>% 
  summarize(`1980-2019` = mean(value, na.rm = TRUE),
            month = unique(month))

# --------
# Best case means
# --------

# 2020 - 2059 Best case
# first, rename variables to be able to combine them later

doy_avg_2020_2059_bc <- future_day %>% 
  filter(year %in% c(2020:2059)) %>%
  select(accumswe_daily_bc:doy) %>% 
  pivot_longer(accumswe_daily_bc,
    #`soil_water_daily_bc`:`aet_daily_bc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>% # new column name to store values)
  mutate(variable = case_when(.$variable == "aet_daily_bc" ~ "aet_daily",
    .$variable == "rain_daily_bc" ~ "rain_daily",
    .$variable == "runoff_daily_bc" ~ "runoff_daily",
    .$variable == "pet_daily_bc" ~ "pet_daily",
    .$variable == "accumswe_daily_bc" ~ "accumswe_daily",
    .$variable == "soil_water_daily_bc" ~ "soil_water_daily",
    .$variable == "agdd_daily_bc" ~ "agdd_daily",
    TRUE ~ "deficit_daily")) %>% 
  group_by(doy, variable) %>% 
  summarize(`2020-2059` = mean(value, na.rm = TRUE),
            month = unique(month)) 


# 2060 - 2099 Best case df
# first, rename variables to be able to combine them later

doy_avg_2060_2099_bc <-  future_day %>% 
  filter(year %in% c(2060:2099)) %>%
  select(accumswe_daily_bc:doy) %>% 
#soil_water_daily_bc:doy) %>%
  pivot_longer(`accumswe_daily_bc`,#`soil_water_daily_bc`:`aet_daily_bc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>%  # new column name to store values) 
  mutate(variable = case_when(.$variable == "aet_daily_bc" ~ "aet_daily",
    .$variable == "rain_daily_bc" ~ "rain_daily",
    .$variable == "runoff_daily_bc" ~ "runoff_daily",
    .$variable == "pet_daily_bc" ~ "pet_daily",
    .$variable == "accumswe_daily_bc" ~ "accumswe_daily",
    .$variable == "soil_water_daily_bc" ~ "soil_water_daily",
    .$variable == "agdd_daily_bc" ~ "agdd_daily",
    TRUE ~ "deficit_daily")) %>% #for grouping by doy
  group_by(doy, variable) %>% 
  summarize(`2060-2099` = mean(value, na.rm = TRUE),
            month = unique(month)) 

#full doy dataframe Best case

doy_avg_bc <- doy_avg_1980_2019 %>% 
  full_join(doy_avg_2020_2059_bc) %>% 
  full_join(doy_avg_2060_2099_bc) %>% 
  pivot_longer(c(`1980-2019`,`2020-2059`,`2060-2099`), # The columns I'm gathering together
               names_to = "decades", # new column name for existing names
               values_to = "value") %>% # new column name to store values 
  na.omit(doy_avg_bc) %>%  # because of the way the dataframe was made, there's NA's for second and third 40, just don't want those there
  pivot_wider(names_from = variable,
              values_from = value)


# --------
# wc means
# --------

# 2020 - 2059 wc df
# first, rename variables to be able to combine them later

doy_avg_2020_2059_wc <- future_day %>% 
  filter(year %in% c(2020:2059)) %>%
  select(accumswe_daily_wc, date:doy) %>% #soil_water_daily_wc:doy) %>% 
  pivot_longer(`accumswe_daily_wc`,#`soil_water_daily_wc`:`aet_daily_wc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>% # new column name to store values)
  mutate(variable = case_when(.$variable == "aet_daily_wc" ~ "aet_daily",
    .$variable == "rain_daily_wc" ~ "rain_daily",
    .$variable == "runoff_daily_wc" ~ "runoff_daily",
    .$variable == "pet_daily_wc" ~ "pet_daily",
    .$variable == "accumswe_daily_wc" ~ "accumswe_daily",
    .$variable == "soil_water_daily_wc" ~ "soil_water_daily",
    .$variable == "agdd_daily_wc" ~ "agdd_daily",
    TRUE ~ "deficit_daily")) %>% 
  group_by(doy, variable) %>% 
  summarize(`2020-2059` = mean(value, na.rm = TRUE),
            month = unique(month)) 


# 2060 - 2099 wc df
# first, rename variables to be able to combine them later

doy_avg_2060_2099_wc <-  future_day %>% 
  filter(year %in% c(2060:2099)) %>%
  select(accumswe_daily_wc, date:doy) %>% #soil_water_daily_wc:doy) %>%
  pivot_longer(`accumswe_daily_wc`,#`soil_water_daily_wc`:`aet_daily_wc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>%  # new column name to store values) 
  mutate(variable = case_when(.$variable == "aet_daily_wc" ~ "aet_daily",
    .$variable == "rain_daily_wc" ~ "rain_daily",
    .$variable == "runoff_daily_wc" ~ "runoff_daily",
    .$variable == "pet_daily_wc" ~ "pet_daily",
    .$variable == "accumswe_daily_wc" ~ "accumswe_daily",
    .$variable == "soil_water_daily_wc" ~ "soil_water_daily",
    .$variable == "agdd_daily_wc" ~ "agdd_daily",
    TRUE ~ "deficit_daily")) %>% 
  group_by(doy, variable) %>% 
  summarize(`2060-2099` = mean(value, na.rm = TRUE),
            month = unique(month)) 


#full day dataset wc

doy_avg_wc <- doy_avg_1980_2019 %>% 
  full_join(doy_avg_2020_2059_wc) %>% 
  full_join(doy_avg_2060_2099_wc) %>% 
  pivot_longer(c(`1980-2019`,`2020-2059`,`2060-2099`), # The columns I'm gathering together
               names_to = "decades", # new column name for existing names
               values_to = "value") %>% # new column name to store values 
  na.omit(doy_avg_wc) %>%  # because of the way the dataframe was made, there's NA's for second and third 40, just don't want those there
  pivot_wider(names_from = variable,
              values_from = value) 


```

```{r}
# -------
# Function for 40 yr chunks - smoothed line graph by doy
# -------


plot_decades_smooth = function(.y) { #start function
  
  max_y_1 <- doy_avg_bc %>%
    full_join(doy_avg_wc) %>%
  select(.y)


max_y_2 <- max(max_y_1[,2], na.rm = TRUE)

max_y <- max_y_2*1.15

  
  exists_.y <- exists(.y, where = doy_avg_bc) #check to see if the variable exists
  
  if(exists_.y == TRUE){ #start if statement Best case
  
  .y_plot_bc <- ggplot(doy_avg_bc) + 
    geom_line(aes(x = as.Date.numeric(doy, origin = "1980-01-01"),
                   y = .data[[.y]],
                   color = decades),
               size = 0.7,
               alpha = 0.4) +
    stat_smooth(size = 1.5,
                se = FALSE,
                aes(x = as.Date.numeric(doy, origin = "1980-01-01"),#allows for month on xaxis
                    y = .data[[.y]],
                    # calling my variable, which I'll name later in the command
                    group = decades,
                    color = decades),
                method = glm,
                family = quasipoisson,
                formula = y ~ ns(x, 16)) +
    theme(legend.title = element_blank())+
    #internet said to do this
    #quasipoisson is some type of statistical analysis type
    #forumula has something to do with the degrees of freedom
    #https://stackoverflow.com/questions/2777053/in-ggplot-restrict-y-to-be-0-in-loess
    # geom_vline(data = doy_avg_bc,
    #            xintercept = doy[.data[[.y]] == max(.data[[.y]])], color='red') +
    labs(color = "Year",
         y = ifelse(.y == "agdd_daily", "Growing Degree Days (C)", "Water (mm)"), 
         # R needs the "" here
         # the ifelse goes after the command you want to change
         #.y is useful because it prevents R from confusing it with something else
         # purrr is much more useful than a for loop here
         # if {} else{} and if_else() both didn't work, but I don't know why
         title = case_when(.y ==  "soil_water_daily" ~ 
                             paste("Soil Water Seasonality", "\n",
                                   "Hotter and wetter", sep = ""), #title based on variable
                           .y == "runoff_daily" ~ 
                             paste("Runoff Seasonality", "\n",
                                   "Hotter and wetter", sep = ""),
                           .y == "rain_daily" ~  
                             paste("Rain Seasonality","\n",
                                   "Hotter and wetter", sep = ""),
                           .y == "agdd_daily" ~ 
                             paste("AGDD Seasonality","\n",
                                   "Hotter and wetter", sep = ""),
                           .y == "accumswe_daily"~ paste(
                              "SWE Seasonality", "\n",
                                   "Hotter and wetter", sep = ""),
                           .y == "pet_daily" ~ paste(
                               "PET Seasonality", "\n",
                               "Hotter and wetter", sep = ""),
                           .y == "deficit_daily" ~ 
                             paste("Deficit Seasonality", "\n",
                                   "Hotter and wetter", sep = ""),
                           TRUE ~ paste(
                               "AET Seasonality", "\n",
                                   "Hotter and wetter", sep = ""))) + 
    scale_color_manual(breaks = c("1980-2019", "2020-2059", "2060-2099"),
                       values = c("#A3B86C", "#EBC944", "#1496BB")) +
    ylim(0, max_y) +
    scale_x_date(as.Date.numeric(doy_avg_bc$doy, origin = "1980-01-01"),
                 breaks = seq(as.Date("1980-01-15"), 
                            as.Date("1980-12-15"), #plots date at midmonth
                            by = "1 month"),
                 date_labels = "%b")#%b is abbreviated, %B is full month name
  # gb <- ggplot_build(.y_plot_bc)
    
# gb <- ggplot_build(.y_plot_bc)
# 
#   vline_data_bc <- 
#     gb$data[[1]] %>% 
#     group_by(group) %>% 
#     summarize(xintercept = x[which(y == max(y))])
#  
#   .y_plot_bc <- .y_plot_bc + geom_vline(aes(xintercept = xintercept), data = vline_data_bc)
  
  
  ggsave(here::here(paste(site, climvar, "40_yr",model_bc_rcp, model_bc, ".png", sep = "_")), width = 7, height = 5) #file name

  print(.y_plot_bc)
  
  } #end if statement for Best case
  
  exists_.y <- exists(.y, where = doy_avg_wc) #check to see if the variable exists
  
  if(exists_.y == TRUE){ #start if statement RCP 8.5
  
  .y_plot_wc <- ggplot(doy_avg_wc) +
    geom_line(aes(x = as.Date.numeric(doy, origin = "1980-01-01"),
                   y = .data[[.y]],
                   color = decades),
               size = 0.7,
               alpha = 0.4) +
    stat_smooth(size = 1.5,
                se = FALSE,
                aes(x = as.Date.numeric(doy, origin = "1980-01-01"),#allows for month on xaxis
                    y = .data[[.y]],
                    # calling my variable, which I'll name later in the command
                    group = decades,
                    color = decades),
                method = glm,
                family = quasipoisson,
                formula = y ~ ns(x, 16)) +
    theme(legend.title = element_blank()) +
        #internet said to do this
    #quasipoisson is some type of statistical analysis type
    #forumula has something to do with the degrees of freedom
    #https://stackoverflow.com/questions/2777053/in-ggplot-restrict-y-to-be-0-in-loess
    #geom_vline(xintercept = doy[.data[[.y]] == max(.data[[.y]])],color='red') +
    labs(color = "Year",
         y = ifelse(.y == "agdd_daily", "Growing Degree Days (C)", "Water (mm)"), 
         # R needs the "" here
         # the ifelse goes after the command you want to change
         #.y is useful because it prevents R from confusing it with something else
         # purrr is much more useful than a for loop here
         # if {} else{} and if_else() both didn't work, but I don't know why
         title = case_when(.y ==  "soil_water_daily" ~ 
                             paste("Soil Water Seasonality", "\n",
                                   "Hotter and drier", sep = ""), #title based on variable
                           .y == "runoff_daily" ~ 
                             paste("Runoff Seasonality", "\n",
                                   "Hotter and drier", sep = ""),
                           .y == "rain_daily" ~  
                             paste("Rain Seasonality", "\n",
                                   "Hotter and drier", sep = ""),
                           .y == "agdd_daily" ~ 
                             paste("AGDD Seasonality", "\n",
                                   "Hotter and drier", sep = ""),
                           .y == "accumswe_daily"~ 
                            paste(
                              "SWE Seasonality", "\n",
                                   "Hotter and drier", sep = ""),
                           .y == "pet_daily" ~ 
                             paste(
                               "Potential Evapotranspiration Seasonality", "\n",
                               "Hotter and drier", sep = ""),
                           .y == "deficit_daily" ~ 
                             paste("Deficit Seasonality", "\n",
                                   "Hotter and drier", sep = ""),
                           TRUE ~ 
                             paste(
                               "Actual Evapotranspiration Seasonality", "\n",
                                   "Hotter and drier", sep = ""))) +
    scale_color_manual(breaks = c("1980-2019", "2020-2059", "2060-2099"),
                       values = c("#A3B86C", "#EBC944", "#1496BB")) +
  ylim(0, max_y)+
    scale_x_date(as.Date.numeric(doy_avg_bc$doy, origin = "1980-01-01"),
                 breaks = seq(as.Date("1980-01-15"), 
                            as.Date("1980-12-15"), #plots date at midmonth
                            by = "1 month"),
                 date_labels = "%b")#%b is abbreviated, %B is full month name
  # gb <- ggplot_build(.y_plot_bc)
  # 
  # vline_data_wc <- 
  #   gb$data[[1]] %>% 
  #   group_by(group) %>% 
  #   summarize(xintercept = x[which(y == max(y))])
  # 
  # .y_plot_wc <- .y_plot_wc + geom_vline(aes(xintercept = xintercept), data = vline_data_wc)
  
  ggsave(here::here(paste(site, climvar, "40_yr",model_wc_rcp, model_wc, ".png", sep = "_")), width = 7, height = 5) #file name
  
  print(.y_plot_wc)
  
  } #end if statement worst case

  
} #end function decades_smooth



# ---------
# function for line graph
# ---------



plot_decades_line = function(.y) { #start function
  
  max_y_1 <- doy_avg_bc %>%
    full_join(doy_avg_wc) %>%
  select(.y)


max_y_2 <- max(max_y_1[,2], na.rm = TRUE)

max_y <- max_y_2*1.15
  
  exists_.y <- exists(.y, where = doy_avg_bc) #check to see if the variable exists
  
  if(exists_.y == TRUE){ #start if statement Best case

.y_plot_bc <- ggplot(doy_avg_bc) + 
    geom_line(size = 1.5,
                aes(x = as.Date.numeric(doy, origin = "1980-01-01"),#plots month on x axis
                    y = .data[[.y]],
                    # calling my variable, which I'll name later in the command
                    group = decades,
                    color = decades)) +
  theme(legend.title = element_blank()) +
    #internet said to do this
    #quasipoisson is some type of statistical analysis type
    #forumula has something to do with the degrees of freedom
    #https://stackoverflow.com/questions/2777053/in-ggplot-restrict-y-to-be-0-in-loess
    # geom_vline(data = doy_avg_bc,
    #            xintercept = doy[.data[[.y]] == max(.data[[.y]])], color='red') +
    labs(color = "Year",
         y = ifelse(.y == "agdd_daily", "Growing Degree Days (C)", "Water (mm)"), 
         # R needs the "" here
         # the ifelse goes after the command you want to change
         #.y is useful because it prevents R from confusing it with something else
         # purrr is much more useful than a for loop here
         # if {} else{} and if_else() both didn't work, but I don't know why
         title = case_when(.y ==  "soil_water_daily" ~ 
                             paste("Soil Water Seasonality", "\n",
                                   "Hotter and wetter", sep = ""), #title based on variable
                           .y == "runoff_daily" ~ 
                             paste("Runoff Seasonality", "\n",
                                   "Hotter and wetter", sep = ""),
                           .y == "rain_daily" ~  
                             paste("Rain Seasonality", "\n",
                                   "Hotter and wetter", sep = ""),
                           .y == "agdd_daily" ~ 
                             paste("AGDD Seasonality", "\n",
                                   "Hotter and wetter", sep = ""),
                           .y == "accumswe_daily"~ 
                            paste(
                              "Peak SWE Seasonality", "\n",
                                   "Hotter and wetter", sep = ""),
                           .y == "pet_daily" ~ 
                             paste(
                               "Potential Evapotranspiration Seasonality", "\n",
                               "Hotter and wetter", sep = ""),
                           .y == "deficit_daily" ~ 
                             paste("Deficit Seasonality", "\n",
                                   "Hotter and wetter", sep = ""),
                           TRUE ~ 
                             paste(
                               "Actual Evapotranspiration Seasonality", "\n",
                                   "Hotter and wetter", sep = ""))) +
    scale_color_manual(breaks = c("1980-2019", "2020-2059", "2060-2099"),
                       values = c("#A3B86C", "#EBC944", "#1496BB")) +
  ylim(NA, max_y) +
    scale_x_date(as.Date.numeric(doy_avg_bc$doy, origin = "1980-01-01"),
                 breaks = seq(as.Date("1980-01-15"), 
                            as.Date("1980-12-15"),#moves breaks to midmonth
                            by = "1 month"),
                 date_labels = "%b")# %b gives abbreviated %B gives full month name
  
  ggsave(here::here(paste(site, climvar, "40_yr_line",model_bc_rcp, model_bc, ".png", sep = "_")), width = 6, height = 4) #file name
  print(.y_plot_bc)
  
  } # end if statement rcp bc
  
  exists_.y <- exists(.y, where = doy_avg_wc) #check to see if the variable exists
  
  if(exists_.y == TRUE){ #start if statement best case
  
  .y_plot_wc <- ggplot(doy_avg_wc) +
    geom_line(size = 1.5,
                aes(x = as.Date.numeric(doy, origin = "1980-01-01"),#allows months to plot on x axis
                    y = .data[[.y]],
                    # calling my variable, which I'll name later in the command
                    group = decades,
                    color = decades)) +
    theme(legend.title = element_blank()) +
    labs(color = "Year",
         y = ifelse(.y == "agdd_daily", "Growing Degree Days (C)", "Water (mm)"), 
         # R needs the "" here
         # the ifelse or case_when goes after the command you want to change
         #.y is useful because it prevents R from confusing it with something else
         title = case_when(.y ==  "soil_water_daily" ~ 
                             paste("Soil Water Seasonality", "\n",
                                   "Hotter and drier", sep = ""), #title based on variable
                           .y == "runoff_daily" ~ 
                             paste("Runoff Seasonality", "\n",
                                   "Hotter and drier", sep = ""),
                           .y == "rain_daily" ~  
                             paste("Rain Seasonality",
                                   "Hotter and drier", sep = ""),
                           .y == "agdd_daily" ~ 
                             paste("AGDD Seasonality", "\n",
                                   "Hotter and drier", sep = ""),
                           .y == "accumswe_daily"~ 
                            paste(
                              "Peak SWE Seasonality", "\n",
                                   "Hotter and drier", sep = ""),
                           .y == "pet_daily" ~ 
                             paste(
                               "Potential Evapotranspiration Seasonality", "\n",
                               "Hotter and drier", sep = ""),
                           .y == "deficit_daily" ~ 
                             paste("Deficit Seasonality", "\n",
                                   "Hotter and drier", sep = ""),
                           TRUE ~ 
                             paste(
                               "Actual Evapotranspiration Seasonality",
                                   "Hotter and drier", sep = ""))) +
    scale_color_manual(breaks = c("1980-2019", "2020-2059", "2060-2099"),
                       values = c("#A3B86C", #turquoise
                                  "#EBC944", #green
                                  "#1496BB")) +#yellow
    ylim(NA, max_y) +
    scale_x_date(as.Date.numeric(doy_avg_bc$doy, origin = "1980-01-01"),
                 breaks = seq(as.Date("1980-01-15"), 
                            as.Date("1980-12-15"),#sets labels at the middle of the month
                            by = "1 month"),
                 date_labels = "%b")
  
  ggsave(here::here(paste(site, climvar, "40_yr_line",model_wc_rcp, model_wc, ".png", sep = "_")), width = 6, height = 4) #file name
  
  print(.y_plot_wc)
  
  } #end if statement RCP 8.5
  
  
  
} #end function decades_line

# call graphs later



  
```


```{r, out.width="50%"}
## Individual Graphs of change over time

plot_annual = function(.y) {
   
   point_low <- annual_values %>%
     filter(variable %in% c(.y)) %>% 
     filter(year == dry_year)
   
   point_high<- annual_values %>%
     filter(variable %in% c(.y)) %>% 
     filter(year == wet_year)
   
   line_low <- point_low$annual_value
   
   line_high <- point_high$annual_value
   
   # ---------------
   # create y limit for graph
   # ---------------
   
    max_y_1 <- annual_values %>%
      filter(variable %in% c(.y))
    
    max_y_2 <- max(max_y_1[,3], na.rm = TRUE)
    
    max_y <- max_y_2*1.15
    
    # ---------------
    # graph
    # ---------------
  
  annual_graph_bc <- ggplot() +
    geom_line(data = annual_values %>% 
                filter(averages %in% c("annual_avg", "annual_avg_bc")) %>% 
                filter(variable == .y), # filter data for historical and bc lines
              aes(x = year, 
                  y = annual_value, 
                  color = averages),
              size = .75) +
    geom_hline(data = point_low, # draws a line at a dry year
               yintercept = line_low, 
               linetype = "dashed",
               color = "#DA621E") +
    geom_hline(data = point_high, # draws a line at a wet year
               yintercept = line_high, 
               linetype = "dashed",
               color = "#1287A8") +
    geom_point(data = point_low, # highlights a dry year point
               aes(x = year, y = annual_value),
               color = "#DA621E",
               alpha =  0.25,
               size = 4) +
    geom_point(data = point_high, # highlights a dry year point
               aes(x = year, y = annual_value),
               color = "#1287A8",
               alpha =  0.25,
               size = 4) +
  labs(title = paste("Annual", .y, "\n", "Hotter and wetter", sep = ""),
       y = ifelse(.y == "agdd_daily", "Growing Degree Days (C)",
                    "Water (mm)")) +
      geom_text(data = point_low, # labels the line
              aes(x = 1967, 
                  y = annual_value,
                  label = paste("Dry year:", year), 
                  vjust = -0.35), # -0.x moves the text up above the line
              color = "#DA621E") +
    geom_text(data = point_high, # labels the line
              aes(x = 1967, 
                  y = annual_value,
                  label = paste("Wet year:", year), 
                  vjust = -0.35), # -0.x moves the text up above the line
              color = "#1287A8") +
    scale_color_manual(name = "", values = c("gray60","#A3B86C"), labels = (c("Historical", paste(model_bc, model_bc_rcp_name)))) + # colors is a named vector, see top of function
 ylim(NA, max_y) +
      xlim(1960.5, NA)
  
  ggsave(here::here(paste(site, climvar, model_bc_rcp, model_bc, "annual.png", sep = "_")), width = 7.5, height = 5) #file name
  
  
  annual_graph_wc <- ggplot() +
    geom_line(data = annual_values %>% 
                filter(averages %in% c("annual_avg", "annual_avg_wc")) %>%
                filter(variable == .y), # filter data for historical and wc lines
              aes(x = year, 
                  y = annual_value, 
                  color = averages),
              size = .75) +
    geom_hline(data = point_low, 
               yintercept = line_low, 
               linetype = "dashed",
               color = "#DA621E") +
    geom_hline(data = point_high, # draws a line at a wet year
               yintercept = line_high, 
               linetype = "dashed",
               color = "#1287A8") +
    geom_point(data = point_low, # highlights a dry year point
               aes(x = year, y = annual_value),
               color = "#DA621E",
               alpha =  0.25,
               size = 4) +
    geom_point(data = point_high, # highlights a dry year point
               aes(x = year, y = annual_value),
               color = "#1287A8",
               alpha =  0.25,
               size = 4) +
  labs(title = paste("Annual ", .y, "\n", model_wc, " ", model_wc_rcp_name, sep = ""),
       y = ifelse(.y == "ADGG", "Growing Degree Days (C)",
                    "Water (mm)")) +
    geom_text(data = point_low, # labels the line
              aes(x = 1967, 
                  y = annual_value,
                  label = paste("Dry year:", year), 
                  vjust = -0.35), # -0.x moves the text up above the line
              color = "#DA621E") +
    geom_text(data = point_high, # labels the line
              aes(x = 1967, 
                  y = annual_value,
                  label = paste("Wet year:", year), 
                  vjust = -0.35), # -0.x moves the text up above the line
              color = "#1287A8") +
    scale_color_manual(name = "", values = c("gray60", "#EBC944"), labels = (c("Historical", paste(model_wc, model_wc_rcp_name)))) + # colors is a named vector, see top of function
  ylim(NA, max_y) +
    xlim(1960.5, NA)
  
  ggsave(here::here(paste(site, climvar, model_wc_rcp, model_wc, "annual_graph_wc.png", sep = "_")), width = 7.5, height = 5) #filename
  
  # return(annual_graph_bc)
  # return(annual_graph_wc) with these two it only prints the 4.5 graph
  
  print(annual_graph_bc)
  print(annual_graph_wc)
  
}
```

```{r, out.width="50%"}
plot_decades_smooth("accumswe_daily")
```
<br>
<br>



```{r, out.width="50%"}
plot_annual("Accumulated SWE")
```
