---
title: "Watershed Balance"
author: "Janelle Christensen"
date: "8/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# -------------
# attach packages
# -------------

library(data.table) 
library(here)
#library(plyr) 
# be careful with this, it causes issues for dplyr::group_by
# I didn't try, but the internet says if you load it before tidyverse, that issue goes away
library(tidyverse)
library(beepr)
library(lubridate)
library(directlabels)
library(data.table)
library(ggbeeswarm)
library(gghalves)
library(directlabels)
library(ggrepel)
library(splines)
library(magrittr)

```


```{r}

# -----------
# set global options
# -----------

#set theme for all graphs
theme_set(theme_classic() + #has the L shape around the graph
            theme(panel.grid = element_blank(), #removes grid lines
                  plot.title = element_text(size = 25), #title of plot text size
                  legend.text = element_text(size = 15), #legend inside text size
                  legend.title = element_text(size = 18), #legend title text size
                  axis.title.y = element_text(size = 15), #changes y axis lable text size
                  axis.title.x = element_text(size = 15),#x axis text size
                  axis.text.x = element_text(size = 15), #changes x-axis text size
                  axis.text.y = element_text(size = 15), #changes y-axis text size
                  legend.position = "top"))  #location of legend
                  

# ------------
# set variables for the data and code
# all of this should be changed before the code is run for a new site
# ------------

site = "little_saddle_mtn" 

lat = 44.702

lon = -110.018

model_bc = "inmcm4" # "best case"

# model options: CCSM4, inmcm4, NorESM1-M, MRI-CGCM3, MIROC5, IPSL-CM5A-LR,  HadGEM2-CC365, GFDL-ESM2G, CanESM2, CSIRO-Mk3-6-0, CNRM-CM5, BNU-ESM

model_bc_rcp_name = "RCP 4.5"



#options "RCP 4.5", "RCP 8.5" 
# IMPORTANT: this is written differently than the data code, it is essentially written into the code to substitute this more "readable" version into the code (in the data code it was rcp45, rcp85)

model_bc_rcp = "rcp45"

# options: "rcp45", "rcp85" this is the SAME RCP as is in the file, just written in the "less readable" way for the file name

model_wc = "HadGEM2-CC365" # "worst case"

# model options: CCSM4, inmcm4, NorESM1-M, MRI-CGCM3, MIROC5, IPSL-CM5A-LR,  HadGEM2-CC365, GFDL-ESM2G, CanESM2, CSIRO-Mk3-6-0, CNRM-CM5, BNU-ESM

model_wc_rcp_name = "RCP 8.5"

#options "RCP 4.5", "RCP 8.5" 
# IMPORTANT: this is written differently than the data code, it is essentially written into the code to substitute this more "readable" version into the code (in the data code it was rcp45, rcpwc)

model_wc_rcp = "rcp85"

# options: "rcp45", "rcp85" this is the SAME RCP as is in the file, just written in the "less readable" way for the file name

past_data = "daymet"

# past_data options: "gridmet", "daymet"
# if you want to use data that will work with the future models, gridmet is a better choice. It doesn't require adjusting for any biases

# ----------
# inmcm4, NorESM1-M downloaded wrong, don't use until updated (noted this 8-5-20)
# ----------

```

```{r}
# Before running the code, create subfolders as needed to save figures

#If you don't want to save the figures, then just comment out ggsave inside of the functions.

# create subfolders for figures

here::here(dir.create(site))

here::here(dir.create(paste(site,
                            "figures",
                            sep = "/")))

here::here(dir.create(paste(site,
                            "figures",
                            paste("lat",lat,"lon",lon,sep = "_"), 
                            sep = "/")))

here::here(dir.create(paste(site,
                            "figures",
                            paste("lat",lat,"lon",lon,sep = "_"),
                            "40_yr_graphs",
                            sep = "/")))
```

This data is based off of `r model_bc` `r model_bc_rcp_name` to display projections for the best case scenario, and `r model_wc``r model_wc_rcp_name` to display projections for the worst case scenario.
```{r}
# -------------
# MONTHLY DATA
# clean data for graphing
# if monthly data wasn't downloaded, change {r} to {r, eval = FALSE } or else this will stop your code from running
# -------------

# I added a line of code that removes variables from the data set that sum to 2
# change this if needed

# -------------
# monthly future data
# -------------


future_month_1 <- read_csv(here::here(site,
                                    "raw_data",
                                    paste("lat",lat,"lon",lon, sep = "_"),
                                    "future_monthly",
                                    paste(site, model_wc, model_wc_rcp, model_bc, model_bc_rcp, "monthly_future.csv", sep = "_")),
                    na = c("-3276.7")) 

date_fm <- future_month_1$date # this is a work around
# want to remove data that has all zeroes conditionally based on lat and lon
# couldn't get data to work to only remove data that had a sum of zero unless removed all non-variable columns

future_month <- future_month_1 %>% 
  select(-lat, -lon, -date) %>% #change this
  select(which(!colSums(., na.rm = TRUE) < 2)) %>% # this removes variable that sum to 2 (i.e. accumswe in a hot climate)
  mutate(date = date_fm,
         year = lubridate::year(date),
         month = lubridate::month(date,
                                  label = TRUE,
                                  abbr = TRUE))

# -------------
# monthly past
# -------------

if(past_data == "daymet"){
  past_month_1 <- read_csv(here::here(site,
                                  "raw_data",
                                  paste("lat",lat,"lon",lon, sep = "_"),
                                  "historical_monthly",
                                  paste(site,"_monthly_",past_data,".csv",
                                        sep = "")),
                             na = c("-3276.7"))%>%  
    mutate(date = lubridate::ymd(paste(year,
                                     month,
                                     sep = "-"),
                               truncated = 1))#fix this when dates are fixed on site
# when/if dates download correctly for monthly historical, this line can be removed
# truncated needs to be here, can't say why it's 1
    } 

if(past_data == "gridmet"){ 
  past_month_1 <- read_csv(here::here( site,
                                  "raw_data",
                                  paste("lat",lat,"lon",lon, sep = "_"),
                                  "historical_monthly",
                                  paste(site,"_monthly_",past_data,".csv", sep = "")),
                             na = c("-3276.7"))
}

date_pm <- past_month_1$date # this is a work around
# want to remove data that has all zeroes conditionally based on lat and lon
# couldn't get data to work to only remove data that had a sum of zero unless removed all non-variable columns

past_month <- past_month_1 %>%
  select(-lat, -lon, -month, - year, -date) %>%
  select(which(!colSums(., na.rm = TRUE) < 2)) %>% # this removes variable that sum to 2 (i.e. accumswe in a hot climate)
  mutate(date = date_pm, #adds date back into the df
         year = lubridate::year(date),
         month = lubridate::month(date,
                                  label = TRUE,
                                  abbr = TRUE))

```

```{r}
# ------------
# DAILY DATA
# clean data for graphing
# ------------

# ------------
# daily future data
# ------------

future_day_1 <- read_csv(here::here( site,
                                  "raw_data",
                                  paste("lat",lat,"lon",lon, sep = "_"),
                                  "future_daily",
                                  paste(site, model_wc, model_wc_rcp, model_bc, model_bc_rcp, "daily_future.csv", sep = "_")),
                    na = c("-3276.7"))

# ---------
# this is only for now
# won't mess up the code if not removed
# named coded wrong when downloading (coded as monthly)
# for some reason there is an extra longitude column, need to fix this
# ---------

#colnames(future_day_1)[]<-c("date", "lat","lon","soil_water_daily_wc", "runoff_daily_wc", "rain_daily_wc", "agdd_daily_wc", "accumswe_daily_wc", "pet_daily_wc", "deficit_daily_wc", "aet_daily_wc", "soil_water_daily_bc", "runoff_daily_bc", "rain_daily_bc", "agdd_daily_bc", "accumswe_daily_bc", "pet_daily_bc", "deficit_daily_bc", "aet_daily_bc")

date_fd <- future_day_1$date
# this is a work around
# want to remove data that has all zeroes conditionally based on site
# couldn't get data to work to only remove data that had a sum of zero unless removed all non-variable columns


future_day <- future_day_1 %>% 
  select(-lat, -lon, -date)  %>%
  select(which(!colSums(., na.rm = TRUE) < 2)) %>% # this removes variable that sum to 2 (i.e. accumswe in a hot climate)
  mutate(date = date_fd,
    year = lubridate::year(date), 
    month = lubridate::month(date,
                             label = TRUE,
                             abbr = TRUE),
    day = lubridate::day(date),
    doy = yday(date))


# ------------
# daily past
# ------------

past_day_1 <- read_csv(here::here(site,
                                  "raw_data",
                                  paste("lat",lat,"lon",lon, sep = "_"),
                                  "historical_daily",
                                  paste(site,"_daily_",past_data,".csv", sep = "")),
                           na = c("-3276.7")) 

date_pd <- past_day_1$date# this is a work around
# want to remove data that has all zeroes conditionally based on lat and lon
# couldn't get data to work to only remove data that had a sum of zero unless removed all non-variable columns

past_day <- past_day_1 %>% 
  select(-lat, -lon, -date)  %>%
  select(which(!colSums(., na.rm = TRUE) < 2)) %>% # this removes variables that sum to 2 (i.e. accumswe in a hot climate)
  mutate(date = date_pd,
         year = lubridate::year(date),
         month = lubridate::month(date,
                                  label = TRUE,
                                  abbr = TRUE),
         day = lubridate::day(date),
         doy = yday(date)) 


```

```{r}
# -------------
# Make site data into long format
# -------------

# -------------
# long format past data daily
# -------------

site_long_past_d <- past_day %>% 
  pivot_longer(`soil_water_daily`:`aet_daily`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>% # new column name to store values
  mutate(variable = case_when(
    .$variable == "runoff_daily" ~ "Runoff",
    #.Svariable calls the variable, then it can be renamed
    .$variable == "agdd_daily" ~ "AGDD",
    .$variable == "soil_water_daily" ~ "Soil Water",
    .$variable == "rain_daily" ~ "Rain",
    .$variable == "accumswe_daily" ~ "Accumulated SWE",
    .$variable == "pet_daily" ~ "PET",
    .$variable == "deficit_daily" ~ "Deficit",
    TRUE ~ "AET" # last ifelse is just labeled as TRUE
  )) %>% 
  mutate(decade = case_when(
    .$year %in% c(1980:1989) ~ "1980s",
    .$year %in% c(1990:1999) ~ "1990s",
    .$year %in% c(2000:2009) ~ "2000s",
    TRUE ~ "2010s"
  )) 

annual_past <- site_long_past_d %>% 
  group_by(variable, year) %>% 
  mutate(annual_avg = mean(value, na.rm = TRUE)) %>% 
  ungroup(variable, year)

# -------------
# long format future data daily
# -------------

site_long_wc <- future_day %>%
  select(soil_water_daily_wc:aet_daily_wc, date:doy) %>% # selecting for variables for 8.5 only
  pivot_longer(`soil_water_daily_wc`:`aet_daily_wc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "rcp_wc") %>%  
  filter(!year == 2100) %>%
  mutate(variable = case_when(
    .$variable == "runoff_daily_wc" ~ "Runoff",
    #.Svariable calls the variable, then it can be renamed
    .$variable == "agdd_daily_wc" ~ "AGDD",
    .$variable == "soil_water_daily_wc" ~ "Soil Water",
    .$variable == "rain_daily_wc" ~ "Rain",
    .$variable == "accumswe_daily_wc" ~ "Accumulated SWE",
    .$variable == "pet_daily_wc" ~ "PET",
    .$variable == "deficit_daily_wc" ~ "Deficit",
    TRUE ~ "AET")) %>% 
  mutate(decade = case_when(
    .$year %in% c(2020:2029) ~ "2020s",
    .$year %in% c(2030:2039) ~ "2030s",
    .$year %in% c(2040:2049) ~ "2040s",
    .$year %in% c(2050:2059) ~ "2050s",
    .$year %in% c(2060:2069) ~ "2060s",
    .$year %in% c(2070:2079) ~ "2070s",
    .$year %in% c(2080:2089) ~ "2080s",
    TRUE ~ "2090s"
  ))

annual_future_wc <- site_long_wc %>% 
  group_by(variable, year) %>% 
  mutate(annual_avg_wc = mean(rcp_wc, na.rm = TRUE)) %>%
  ungroup(year, variable) 

  
  
site_long_bc <- future_day %>% 
  select(soil_water_daily_bc:aet_daily_bc, date:doy) %>% #selecting for 4.5 only
  pivot_longer(`soil_water_daily_bc`:`aet_daily_bc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "rcp_bc") %>% 
  filter(!year == 2100) %>% 
  mutate(variable = case_when(
    .$variable == "runoff_daily_bc" ~ "Runoff",
    #.Svariable calls the variable, then it can be renamed
    .$variable == "agdd_daily_bc" ~ "AGDD",
    .$variable == "soil_water_daily_bc" ~ "Soil Water",
    .$variable == "rain_daily_bc" ~ "Rain",
    .$variable == "accumswe_daily_bc" ~ "Accumulated SWE",
    .$variable == "pet_daily_bc" ~ "PET",
    .$variable == "deficit_daily_bc" ~ "Deficit",
    TRUE ~ "AET" # last ifelse is just labeled as TRUE
  )) %>% 
  mutate(decade = case_when(
    .$year %in% c(2020:2029) ~ "2020s",
    .$year %in% c(2030:2039) ~ "2030s",
    .$year %in% c(2040:2049) ~ "2040s",
    .$year %in% c(2050:2059) ~ "2050s",
    .$year %in% c(2060:2069) ~ "2060s",
    .$year %in% c(2070:2079) ~ "2070s",
    .$year %in% c(2080:2089) ~ "2080s",
    TRUE ~ "2090s"
  ))

annual_future_bc <- site_long_bc %>% 
   group_by(variable, year) %>% 
  mutate(annual_avg_bc = mean(rcp_bc, na.rm = TRUE)) %>%
  ungroup(year, variable) 


annual_future <- annual_future_bc %>%
  full_join(annual_future_wc)

```

# Histograms and qq plots to look at data spread

```{r, include = FALSE, eval = FALSE}

# ------------
# histogram for future data
# ------------


plot_histogram_future = function(.y) {
  
  site_long_.y <- annual_future %>%
    filter(decade %in% (.y))
  
.y_hist_bc <- ggplot(data = site_long_.y) +
    geom_histogram(aes(x = rcp_bc), binwidth = 10) +
    facet_wrap(~variable)+
    labs(title = paste(.y, model_bc_rcp_name))

.y_hist_wc <- ggplot(data = site_long_.y) +
    geom_histogram(aes(x = rcp_wc), binwidth = 10) +
    facet_wrap(~variable)+
    labs(title = paste(.y, model_wc_rcp_name))
  
  print(.y_hist_bc)
  print(.y_hist_wc)
}

# ------------
# histogram for past data
# ------------

plot_histogram_past = function(.y) {
  
  site_long_.y <- annual_past %>%
    filter(decade %in% (.y))
  
.y_hist_past <- ggplot(data = site_long_.y) +
    geom_histogram(aes(x = value), binwidth = 10) +
    facet_wrap(~variable)+
    labs(title = .y)
  
  print(.y_hist_past)
}

plot_histogram_past("1980s")
plot_histogram_past("1990s")
plot_histogram_past("2000s")
plot_histogram_past("2010s")
plot_histogram_future("2020s")
plot_histogram_future("2030s")
plot_histogram_future("2040s")
plot_histogram_future("2050s")
plot_histogram_future("2060s")
plot_histogram_future("2070s")
plot_histogram_future("2080s")
plot_histogram_future("2090s")


#-------------
# look at data removing months that aren't rainy
# ------------

# ------------
# histogram for future data rainy months
# ------------

plot_rainy_hist_future = function(.y) {
  
  site_long_.y <- annual_future %>%
    filter(decade %in% (.y),
           month %in% c("May", "Jun", "Jul", "Aug", "Sep"))
  
.y_hist_bc <- ggplot(data = site_long_.y) +
    geom_histogram(aes(x = rcp_bc), binwidth = 10) +
    facet_wrap(~variable)+
    labs(title = paste(.y, "May - Sep", model_bc_rcp_name))

.y_hist_wc <- ggplot(data = site_long_.y) +
    geom_histogram(aes(x = rcp_wc), binwidth = 10) +
    facet_wrap(~variable)+
    labs(title = paste(.y, "May - Sep" model_wc_rcp_name))
  
  print(.y_hist_bc)
  print(.y_hist_wc)
}

# ------------
# histogram for past data rainy months
# ------------

plot_rainy_hist_past = function(.y) {
  
  site_long_.y <- annual_past %>%
    filter(decade %in% (.y),
           month %in% c("May", "Jun", "Jul", "Aug", "Sep"))
  
.y_hist_past <- ggplot(data = site_long_.y) +
    geom_histogram(aes(x = value), binwidth = 10) +
    facet_wrap(~variable)+
    labs(title = paste(.y, "May - Sep"))
  
  print(.y_hist_past)
}

plot_rainy_hist_past("1980s")
plot_rainy_hist_past("1990s")
plot_rainy_hist_past("2000s")
plot_rainy_hist_past("2010s")
plot_rainy_hist_future("2020s")
plot_rainy_hist_future("2030s")
plot_rainy_hist_future("2040s")
plot_rainy_hist_future("2050s")
plot_rainy_hist_future("2060s")
plot_rainy_hist_future("2070s")
plot_rainy_hist_future("2080s")
plot_rainy_hist_future("2090s")

# ---------
# qq plots of the data to look at data normalcy
# does it follow expected values?
# ---------

# ---------
# qq plots of future data
# ---------

plot_qq_future = function(.y) {
  
  site_long_.y <- annual_future %>%
    filter(decade %in% (.y))
  
.y_qq_bc <- ggplot(data = site_long_.y) +
    geom_qq(aes(sample = rcp_bc)) +
    facet_wrap(~variable, scales = "free")+
    labs(title = paste(.y, model_bc_rcp_name))

.y_qq_wc <- ggplot(data = site_long_.y) +
    geom_qq(aes(sample = rcp_wc)) +
    facet_wrap(~variable, scales = "free")+
    labs(title = paste(.y, model_wc_rcp_name))
  
  print(.y_qq_bc)
  print(.y_qq_wc)
}

# ----------
# qq plots of past data
# ----------

plot_qq_past = function(.y) {
  
  site_long_.y <- annual_past %>%
    filter(decade %in% (.y))
  
.y_qq_past <- ggplot(data = site_long_.y) +
    geom_qq(aes(sample = value)) +
    facet_wrap(~variable, scales = "free")+
    labs(title = .y)

  print(.y_qq_past)
}

plot_qq_past("1980s")
plot_qq_past("1990s")
plot_qq_past("2000s")
plot_qq_past("2010s")
plot_qq_future("2020s")
plot_qq_future("2030s")
plot_qq_future("2040s")
plot_qq_future("2050s")
plot_qq_future("2060s")
plot_qq_future("2070s")
plot_qq_future("2080s")
plot_qq_future("2090s")

# ----------
# qq plots of future rainy month data
# ----------

plot_rainy_qq_future = function(.y) {
  
  site_long_.y <- annual_future %>%
    filter(decade %in% (.y),
           month %in% c("May", "Jun", "Jul", "Aug", "Sep"))
  
.y_qq_bc <- ggplot(data = site_long_.y) +
    geom_qq(aes(sample = rcp_bc)) +
    facet_wrap(~variable, scales = "free")+
    labs(title = paste(.y, "May - Sep", model_bc_rcp_name))

.y_qq_wc <- ggplot(data = site_long_.y) +
    geom_qq(aes(sample = rcp_wc)) +
    facet_wrap(~variable, scales = "free")+
    labs(title = paste(.y, "May - Sep", model_wc_rcp_name))
  
  print(.y_qq_bc)
  print(.y_qq_wc)
}

# ----------
# qq for past rainy month data
# ----------

plot_rainy_qq_past = function(.y) {
  
  site_long_.y <- annual_past %>%
    filter(decade %in% (.y),
           month %in% c("May", "Jun", "Jul", "Aug", "Sep"))
  
.y_qq_past <- ggplot(data = site_long_.y) +
    geom_qq(aes(sample = value)) +
    facet_wrap(~variable, scales = "free")+
    labs(title = paste(.y, "May - Sep"))
  
  print(.y_qq_past)
}

plot_rainy_qq_past("1980s")
plot_rainy_qq_past("1990s")
plot_rainy_qq_past("2000s")
plot_rainy_qq_past("2010s")
plot_rainy_qq_future("2020s")
plot_rainy_qq_future("2030s")
plot_rainy_qq_future("2040s")
plot_rainy_qq_future("2050s")
plot_rainy_qq_future("2060s")
plot_rainy_qq_future("2070s")
plot_rainy_qq_future("2080s")
plot_rainy_qq_future("2090s")


```

## Graphs for 40 yr. period, shifts in timing of events
```{r}

# --------
# clean data for 40 yr graphs
# --------

day_join_1980_2019 <-  past_day %>% 
  filter(year %in% c(1980:2019)) %>%
  pivot_longer(`soil_water_daily`:`aet_daily`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") # new column name to store values) 

day_join_1980_2019_d <- day_join_1980_2019 %>% #for grouping by doy
  group_by(doy, variable) %>% 
  summarize(`1980-2019` = mean(value, na.rm = TRUE))

# --------
# Best case means
# --------

# 2020 - 2059 Best case
# first, rename variables to be able to combine them later

day_join_2020_2059_bc <- future_day %>% 
  filter(year %in% c(2020:2059)) %>%
  select(soil_water_daily_bc:doy) %>% 
  pivot_longer(`soil_water_daily_bc`:`aet_daily_bc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>% # new column name to store values)
  mutate(variable = case_when(.$variable == "aet_daily_bc" ~ "aet_daily",
    .$variable == "rain_daily_bc" ~ "rain_daily",
    .$variable == "runoff_daily_bc" ~ "runoff_daily",
    .$variable == "pet_daily_bc" ~ "pet_daily",
    .$variable == "accumswe_daily_bc" ~ "accumswe_daily",
    .$variable == "soil_water_daily_bc" ~ "soil_water_daily",
    .$variable == "agdd_daily_bc" ~ "agdd_daily",
    TRUE ~ "deficit_daily")) 

#for grouping by doy

day_join_2020_2059_bc_d <- day_join_2020_2059_bc %>% 
  group_by(doy, variable) %>% 
  summarize(`2020-2059` = mean(value, na.rm = TRUE)) 


# 2060 - 2099 Best case df
# first, rename variables to be able to combine them later

day_join_2060_2099_bc <-  future_day %>% 
  filter(year %in% c(2060:2099)) %>%
  select(soil_water_daily_bc:doy) %>%
  pivot_longer(`soil_water_daily_bc`:`aet_daily_bc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>%  # new column name to store values) 
  mutate(variable = case_when(.$variable == "aet_daily_bc" ~ "aet_daily",
    .$variable == "rain_daily_bc" ~ "rain_daily",
    .$variable == "runoff_daily_bc" ~ "runoff_daily",
    .$variable == "pet_daily_bc" ~ "pet_daily",
    .$variable == "accumswe_daily_bc" ~ "accumswe_daily",
    .$variable == "soil_water_daily_bc" ~ "soil_water_daily",
    .$variable == "agdd_daily_bc" ~ "agdd_daily",
    TRUE ~ "deficit_daily"))

#for grouping by doy

day_join_2060_2099_bc_d <- day_join_2060_2099_bc %>% #for grouping by doy
  group_by(doy, variable) %>% 
  summarize(`2060-2099` = mean(value, na.rm = TRUE)) 

#full doy dataframe Best case

day_join_bc_d <- day_join_1980_2019_d %>% 
  full_join(day_join_2020_2059_bc_d) %>% 
  full_join(day_join_2060_2099_bc_d) %>% 
  pivot_longer(`1980-2019`:`2060-2099`, # The columns I'm gathering together
               names_to = "decades", # new column name for existing names
               values_to = "value") %>% # new column name to store values 
  na.omit(day_join_bc_d) %>%  # because of the way the dataframe was made, there's NA's for second and third 40, just don't want those there
  pivot_wider(names_from = variable,
              values_from = value) 


# --------
# wc means
# --------

# 2020 - 2059 wc df
# first, rename variables to be able to combine them later

day_join_2020_2059_wc <- future_day %>% 
  filter(year %in% c(2020:2059)) %>%
  select(soil_water_daily_wc:doy) %>% 
  pivot_longer(`soil_water_daily_wc`:`aet_daily_wc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>% # new column name to store values)
  mutate(variable = case_when(.$variable == "aet_daily_wc" ~ "aet_daily",
    .$variable == "rain_daily_wc" ~ "rain_daily",
    .$variable == "runoff_daily_wc" ~ "runoff_daily",
    .$variable == "pet_daily_wc" ~ "pet_daily",
    .$variable == "accumswe_daily_wc" ~ "accumswe_daily",
    .$variable == "soil_water_daily_wc" ~ "soil_water_daily",
    .$variable == "agdd_daily_wc" ~ "agdd_daily",
    TRUE ~ "deficit_daily"))   
  
#for grouping by doy
  
day_join_2020_2059_wc_d <- day_join_2020_2059_wc %>% 
  group_by(doy, variable) %>% 
  summarize(`2020-2059` = mean(value, na.rm = TRUE)) 


# 2060 - 2099 wc df
# first, rename variables to be able to combine them later

day_join_2060_2099_wc <-  future_day %>% 
  filter(year %in% c(2060:2099)) %>%
  select(soil_water_daily_wc:doy) %>%
  pivot_longer(`soil_water_daily_wc`:`aet_daily_wc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>%  # new column name to store values) 
  mutate(variable = case_when(.$variable == "aet_daily_wc" ~ "aet_daily",
    .$variable == "rain_daily_wc" ~ "rain_daily",
    .$variable == "runoff_daily_wc" ~ "runoff_daily",
    .$variable == "pet_daily_wc" ~ "pet_daily",
    .$variable == "accumswe_daily_wc" ~ "accumswe_daily",
    .$variable == "soil_water_daily_wc" ~ "soil_water_daily",
    .$variable == "agdd_daily_wc" ~ "agdd_daily",
    TRUE ~ "deficit_daily"))

#for grouping by doy

day_join_2060_2099_wc_d <- day_join_2060_2099_wc %>% 
  group_by(doy, variable) %>% 
  summarize(`2060-2099` = mean(value, na.rm = TRUE)) 


#full day dataset wc

day_join_wc_d <- day_join_1980_2019_d %>% 
  full_join(day_join_2020_2059_wc_d) %>% 
  full_join(day_join_2060_2099_wc_d) %>% 
  pivot_longer(`1980-2019`:`2060-2099`, # The columns I'm gathering together
               names_to = "decades", # new column name for existing names
               values_to = "value") %>% # new column name to store values 
  na.omit(day_join_wc_d) %>%  # because of the way the dataframe was made, there's NA's for second and third 40, just don't want those there
  pivot_wider(names_from = variable,
              values_from = value) 


```

```{r}

# Month data
month_join_1980_2019 <- past_month %>% 
  pivot_longer(`soil_water_monthly`:`aet_monthly`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>% # new column name to store values
  mutate(variable = case_when(
    .$variable == "runoff_monthly" ~ "Runoff",
    #.Svariable calls the variable, then it can be renamed
    .$variable == "agdd_monthly" ~ "AGDD",
    .$variable == "soil_water_monthly" ~ "Soil Water",
    .$variable == "rain_monthly" ~ "Rain",
    .$variable == "accumswe_monthly" ~ "Accumulated SWE",
    .$variable == "pet_monthly" ~ "PET",
    .$variable == "deficit_monthly" ~ "Deficit",
    TRUE ~ "AET" # last ifelse is just labeled as TRUE
  )) %>% 
  mutate("1980-2019" = value) %>% 
  select(-value)

# --------
# Best case month data in long format
# --------

# 2020 - 2059 Best case
# first, rename variables to be able to combine them later

month_join_2020_2059_bc <- future_month %>% 
  filter(year %in% c(2020:2059)) %>%
  select(soil_water_monthly_bc:month) %>% 
  pivot_longer(`soil_water_monthly_bc`:`aet_monthly_bc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>% # new column name to store values)
  mutate(variable = case_when(.$variable == "aet_monthly_bc" ~ "AET",
    .$variable == "rain_monthly_bc" ~ "Rain",
    .$variable == "runoff_monthly_bc" ~ "Runoff",
    .$variable == "pet_monthly_bc" ~ "PET",
    .$variable == "accumswe_monthly_bc" ~ "Accumulated SWE",
    .$variable == "soil_water_monthly_bc" ~ "Soil Water",
    .$variable == "agdd_monthly_bc" ~ "AGDD",
    TRUE ~ "Deficit")) %>% 
  mutate("2020-2059" = value) %>% 
  select(-value)
  


# 2060 - 2099 Best case df
# first, rename variables to be able to combine them later

month_join_2060_2099_bc <-  future_month %>% 
  filter(year %in% c(2060:2099)) %>%
  select(soil_water_monthly_bc:month) %>%
  pivot_longer(`soil_water_monthly_bc`:`aet_monthly_bc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>%  # new column name to store values) 
  mutate(variable = case_when(.$variable == "aet_monthly_bc" ~ "AET",
    .$variable == "rain_monthly_bc" ~ "Rain",
    .$variable == "runoff_monthly_bc" ~ "Runoff",
    .$variable == "pet_monthly_bc" ~ "PET",
    .$variable == "accumswe_monthly_bc" ~ "Accumulated SWE",
    .$variable == "soil_water_monthly_bc" ~ "Soil Water",
    .$variable == "agdd_monthly_bc" ~ "AGDD",
    TRUE ~ "Deficit"))%>% 
  mutate(`2060-2099` = value) %>% 
  select(-value)

#full doy dataframe Best case

month_join_bc <- month_join_1980_2019 %>% 
  full_join(month_join_2020_2059_bc) %>% 
  full_join(month_join_2060_2099_bc) %>% 
  pivot_longer(`1980-2019`:`2060-2099`, # The columns I'm gathering together
               names_to = "decades", # new column name for existing names
               values_to = "value") %>% # new column name to store values 
  na.omit(month_join_bc_m)# because of the way the dataframe was made, there's NA's for second and third 40, just don't want those there


# --------
# wc means
# --------

# 2020 - 2059 worst case
# first, rename variables to be able to combine them later

month_join_2020_2059_wc <- future_month %>% 
  filter(year %in% c(2020:2059)) %>%
  select(soil_water_monthly_wc:aet_monthly_wc, date:month) %>% 
  pivot_longer(`soil_water_monthly_wc`:`aet_monthly_wc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>% # new column name to store values)
  mutate(variable = case_when(.$variable == "aet_monthly_wc" ~ "AET",
    .$variable == "rain_monthly_wc" ~ "Rain",
    .$variable == "runoff_monthly_wc" ~ "Runoff",
    .$variable == "pet_monthly_wc" ~ "PET",
    .$variable == "accumswe_monthly_wc" ~ "Accumulated SWE",
    .$variable == "soil_water_monthly_wc" ~ "Soil Water",
    .$variable == "agdd_monthly_wc" ~ "AGDD",
    TRUE ~ "Deficit")) %>% 
  mutate("2020-2059" = value) %>% 
  select(-value)
  


# 2060 - 2099 worst case df
# first, rename variables to be able to combine them later

month_join_2060_2099_wc <-  future_month %>% 
  filter(year %in% c(2060:2099)) %>%
  select(soil_water_monthly_wc:aet_monthly_wc, date:month) %>%
  pivot_longer(`soil_water_monthly_wc`:`aet_monthly_wc`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>%  # new column name to store values) 
  mutate(variable = case_when(.$variable == "aet_monthly_wc" ~ "AET",
    .$variable == "rain_monthly_wc" ~ "Rain",
    .$variable == "runoff_monthly_wc" ~ "Runoff",
    .$variable == "pet_monthly_wc" ~ "PET",
    .$variable == "accumswe_monthly_wc" ~ "Accumulated SWE",
    .$variable == "soil_water_monthly_wc" ~ "Soil Water",
    .$variable == "agdd_monthly_wc" ~ "AGDD",
    TRUE ~ "Deficit"))%>% 
  mutate(`2060-2099` = value) %>% 
  select(-value)

#full doy dataframe worst case

month_join_wc <- month_join_1980_2019 %>% 
  full_join(month_join_2020_2059_wc) %>% 
  full_join(month_join_2060_2099_wc) %>% 
  pivot_longer(`1980-2019`:`2060-2099`, # The columns I'm gathering together
               names_to = "decades", # new column name for existing names
               values_to = "value") %>% # new column name to store values 
  na.omit(month_join_wc_m)# because of the way the dataframe was made, there's NA's for second and third 40, just don't want those there

```


```{r}
# -------
# Function for 40 yr chunks - line graph by doy
# -------


plot_decades_smooth = function(.y) { #start function
  
  max_y_1 <- day_join_bc_d %>%
    full_join(day_join_wc_d) %>%
  select(.y)


max_y_2 <- max(max_y_1[,2], na.rm = TRUE)

max_y <- max_y_2*1.15

  
  exists_.y <- exists(.y, where = day_join_bc_d) #check to see if the variable exists
  
  if(exists_.y == TRUE){ #start if statement Best case
  
  .y_plot_bc <- ggplot(day_join_bc_d) + 
    geom_smooth(size = 1.5,
                se = FALSE,
                aes(x = doy,
                    y = .data[[.y]],
                    # calling my variable, which I'll name later in the command
                    group = decades,
                    color = decades),
                method = glm,
                family = quasipoisson,
                formula = y ~ ns(x, 16)) +
    #internet said to do this
    #quasipoisson is some type of statistical analysis type
    #forumula has something to do with the degrees of freedom
    #https://stackoverflow.com/questions/2777053/in-ggplot-restrict-y-to-be-0-in-loess
    # geom_vline(data = day_join_bc_d,
    #            xintercept = doy[.data[[.y]] == max(.data[[.y]])], color='red') +
    labs(x = "Month",
         color = "Year",
         y = ifelse(.y == "agdd_daily", "Growing Degree Days (C)", "Water (mm)"), 
         # R needs the "" here
         # the ifelse goes after the command you want to change
         #.y is useful because it prevents R from confusing it with something else
         # purrr is much more useful than a for loop here
         # if {} else{} and if_else() both didn't work, but I don't know why
         title = case_when(.y ==  "soil_water_daily" ~ paste("Soil Water",
                                                             model_bc,                                                             model_bc_rcp_name), #title based on variable
                           .y == "runoff_daily" ~ paste("Runoff",
                                                        model_bc,
                                                        model_bc_rcp_name),
                           .y == "rain_daily" ~  paste("Rain",
                                                       model_bc,
                                                       model_bc_rcp_name),
                           .y == "agdd_daily" ~ paste("AGDD",
                                                      model_bc,
                                                      model_bc_rcp_name),
                           .y == "accumswe_daily"~ paste("Accumulated SWE",
                                                         model_bc,
                                                         model_bc_rcp_name),
                           .y == "pet_daily" ~ paste("Potential Evapotranspiration", 
                                                     model_bc,
                                                     model_bc_rcp_name),
                           .y == "deficit_daily" ~ paste("Deficit",
                                                         model_bc,
                                                         model_bc_rcp_name),
                           TRUE ~ paste("Actual Evapotranspiration",
                                        model_bc_rcp_name))) + 
    scale_color_manual(breaks = c("1980-2019", "2020-2059", "2060-2099"),
                       values = c("turquoise4", "darkolivegreen3", "darkgoldenrod3"))  +
  ylim(0, max_y)
  
  ggsave(here::here(site, # site subfolder
                    "figures", #sub folder
                    paste("lat",lat,"lon",lon, sep = "_"),
                    "40_yr_graphs", # subfolder
                    paste(.y, "40_yr", model_bc_rcp, ".png", sep = "_"))) #file name
  
  print(.y_plot_bc)
  
  } #end if statement for Best case
  
  exists_.y <- exists(.y, where = day_join_wc_d) #check to see if the variable exists
  
  if(exists_.y == TRUE){ #start if statement RCP 8.5
  
  .y_plot_wc <- ggplot(day_join_wc_d) +
    stat_smooth(size = 1.5,
                se = FALSE,
                aes(x = doy,
                    y = .data[[.y]],
                    # calling my variable, which I'll name later in the command
                    group = decades,
                    color = decades),
                method = glm,
                family = quasipoisson,
                formula = y ~ ns(x, 16)) +
        #internet said to do this
    #quasipoisson is some type of statistical analysis type
    #forumula has something to do with the degrees of freedom
    #https://stackoverflow.com/questions/2777053/in-ggplot-restrict-y-to-be-0-in-loess
    #geom_vline(xintercept = doy[.data[[.y]] == max(.data[[.y]])],color='red') +
    labs(x = "Month",
         color = "Year",
         y = ifelse(.y == "agdd_daily", "Growing Degree Days (C)", "Water (mm)"), 
         # R needs the "" here
         # the ifelse goes after the command you want to change
         #.y is useful because it prevents R from confusing it with something else
         # purrr is much more useful than a for loop here
         # if {} else{} and if_else() both didn't work, but I don't know why
         title = case_when(.y ==  "soil_water_daily" ~ paste("Soil Water",
                                                             model_wc,                                                             model_wc_rcp_name), #title based on variable
                           .y == "runoff_daily" ~ paste("Runoff",
                                                        model_wc,
                                                        model_wc_rcp_name),
                           .y == "rain_daily" ~  paste("Rain",
                                                       model_wc,
                                                       model_wc_rcp_name),
                           .y == "agdd_daily" ~ paste("AGDD",
                                                      model_wc,
                                                      model_wc_rcp_name),
                           .y == "accumswe_daily"~ paste("Accumulated SWE",
                                                         model_wc,
                                                         model_wc_rcp_name),
                           .y == "pet_daily" ~ paste("Potential Evapotranspiration", 
                                                     model_wc,
                                                     model_wc_rcp_name),
                           .y == "deficit_daily" ~ paste("Deficit",
                                                         model_wc,
                                                         model_wc_rcp_name),
                           TRUE ~ paste("Actual Evapotranspiration",
                                        model_wc,
                                        model_wc_rcp_name))) +
    scale_color_manual(breaks = c("1980-2019", "2020-2059", "2060-2099"),
                       values = c("turquoise4", "darkolivegreen3", "darkgoldenrod3")) +
  ylim(0, max_y)
  
  ggsave(here::here(site, #site subfolder
                    "figures", #top folder
                    paste("lat",lat,"lon",lon, sep = "_"),
                    "40_yr_graphs", # subfolder
                    paste(.y, "40_yr", model_wc_rcp, ".png", sep = "_"))) #file name
  
  print(.y_plot_wc)
  
  } #end if statement worst case

  
} #end function decades_smooth



# ---------
# function for line graph
# ---------



plot_decades_line = function(.y) { #start function
  
  exists_.y <- exists(.y, where = day_join_bc_d) #check to see if the variable exists
  
  if(exists_.y == TRUE){ #start if statement Best case

.y_plot_bc <- ggplot(day_join_bc_d) + 
    geom_line(size = 1.5,
                aes(x = doy,
                    y = .data[[.y]],
                    # calling my variable, which I'll name later in the command
                    group = decades,
                    color = decades)) +
    #internet said to do this
    #quasipoisson is some type of statistical analysis type
    #forumula has something to do with the degrees of freedom
    #https://stackoverflow.com/questions/2777053/in-ggplot-restrict-y-to-be-0-in-loess
    # geom_vline(data = day_join_bc_d,
    #            xintercept = doy[.data[[.y]] == max(.data[[.y]])], color='red') +
    labs(x = "Day of Year",
         color = "Year",
         y = ifelse(.y == "agdd_daily", "Growing Degree Days (C)", "Water (mm)"), 
         # R needs the "" here
         # the ifelse goes after the command you want to change
         #.y is useful because it prevents R from confusing it with something else
         # purrr is much more useful than a for loop here
         # if {} else{} and if_else() both didn't work, but I don't know why
         title = case_when(.y ==  "soil_water_daily" ~ paste("Soil Water",
                                                             model_bc,                                                             model_bc_rcp_name), #title based on variable
                           .y == "runoff_daily" ~ paste("Runoff",
                                                        model_bc,
                                                        model_bc_rcp_name),
                           .y == "rain_daily" ~  paste("Rain",
                                                       model_bc,
                                                       model_bc_rcp_name),
                           .y == "agdd_daily" ~ paste("AGDD",
                                                      model_bc,
                                                      model_bc_rcp_name),
                           .y == "accumswe_daily"~ paste("Accumulated SWE",
                                                         model_bc,
                                                         model_bc_rcp_name),
                           .y == "pet_daily" ~ paste("Potential Evapotranspiration", 
                                                     model_bc,
                                                     model_bc_rcp_name),
                           .y == "deficit_daily" ~ paste("Deficit",
                                                         model_bc,
                                                         model_bc_rcp_name),
                           TRUE ~ paste("Actual Evapotranspiration",
                                        model_bc,
                                        model_bc_rcp_name))) +
    scale_color_manual(breaks = c("1980-2019", "2020-2059", "2060-2099"),
                       values = c("turquoise4", "darkolivegreen3", "darkgoldenrod3"))
  
  ggsave(here::here(site, # site subfolder
                    "figures", #sub folder
                    paste("lat",lat,"lon",lon, sep = "_"),
                    "40_yr_graphs", # subfolder
                    paste(.y, "40_yr_line",model_bc_rcp, ".png", sep = "_"))) #file name
  print(.y_plot_bc)
  
  } # end if statement rcp bc
  
  exists_.y <- exists(.y, where = day_join_wc_d) #check to see if the variable exists
  
  if(exists_.y == TRUE){ #start if statement best case
  
  .y_plot_wc <- ggplot(day_join_wc_d) +
    geom_line(size = 1.5,
                aes(x = doy,
                    y = .data[[.y]],
                    # calling my variable, which I'll name later in the command
                    group = decades,
                    color = decades)) +
    #internet said to do this
    #quasipoisson is some type of statistical analysis type
    #forumula has something to do with the degrees of freedom
    #https://stackoverflow.com/questions/2777053/in-ggplot-restrict-y-to-be-0-in-loess
    #geom_vline(xintercept = doy[.data[[.y]] == max(.data[[.y]])],color='red') +
    labs(x = "Day of Year",
         color = "Year",
         y = ifelse(.y == "agdd_daily", "Growing Degree Days (C)", "Water (mm)"), 
         # R needs the "" here
         # the ifelse or case_when goes after the command you want to change
         #.y is useful because it prevents R from confusing it with something else
         title = case_when(.y ==  "soil_water_daily" ~ paste("Soil Water",
                                                             model_wc,                                                             model_wc_rcp_name), #title based on variable
                           .y == "runoff_daily" ~ paste("Runoff",
                                                        model_wc,
                                                        model_wc_rcp_name),
                           .y == "rain_daily" ~  paste("Rain",
                                                       model_wc,
                                                       model_wc_rcp_name),
                           .y == "agdd_daily" ~ paste("AGDD",
                                                      model_wc,
                                                      model_wc_rcp_name),
                           .y == "accumswe_daily"~ paste("Accumulated SWE",
                                                         model_wc,
                                                         model_wc_rcp_name),
                           .y == "pet_daily" ~ paste("Potential Evapotranspiration", 
                                                     model_wc,
                                                     model_wc_rcp_name),
                           .y == "deficit_daily" ~ paste("Deficit",
                                                         model_wc,
                                                         model_wc_rcp_name),
                           TRUE ~ paste("Actual Evapotranspiration",
                                        model_wc,
                                        model_wc_rcp_name))) +
    scale_color_manual(breaks = c("1980-2019", "2020-2059", "2060-2099"),
                       values = c("turquoise4", "darkolivegreen3", "darkgoldenrod3"))
  
  ggsave(here::here(site, #site subfolder
                    "figures", #top folder
                    paste("lat",lat,"lon",lon, sep = "_"),
                    "40_yr_graphs", # subfolder
                    paste(.y, "40_yr_line",model_wc_rcp, ".png", sep = "_"))) #file name
  
  print(.y_plot_wc)
  
  } #end if statement RCP 8.5
  
  
  
} #end function decades_line

```


```{r, out.width="50%"}

plot_decades_smooth("soil_water_daily")
plot_decades_smooth("runoff_daily")
plot_decades_smooth("rain_daily")
plot_decades_smooth("accumswe_daily")
plot_decades_smooth("pet_daily")
plot_decades_smooth("deficit_daily")
plot_decades_smooth("aet_daily")
# plot_decades_line("agdd_daily") - fix later, this data is bad - shouldn't plot 8-20-20

```



## Annual Average over time

```{r, fig.cap="Figure 1. Annual averages over time. The gray line represents historical data modeled from Daymet climate data, the turquoise line represents RCP 4.5 and the yellow line represents RCP 8.5"}

annual_values <- annual_past %>%
  full_join(annual_future_bc) %>% 
  full_join(annual_future_wc) %>%
  select(year, variable, annual_avg, annual_avg_bc, annual_avg_wc) %>% 
  pivot_longer(`annual_avg`:`annual_avg_wc`,
               names_to = "averages", # new column name for existing names
               values_to = "value") %>% 
  na.omit(annual_values) %>% # because of the way the dataframe was made, there are NA's for the future averages, just don't want those there
  group_by(year, variable) %>% 
  summarize(value = unique(value), averages = unique(averages)) 
# first() allows me to keep the first observation from that grouped dataset, and allows me to keep columns so that there is only one observation per year per variable, unique keeps unique observations in that column



ggplot() +
  geom_line(data = annual_values, aes(x = year,
                                      y = value,
                                      color = averages),
            size = 0.6) +
  facet_wrap(~variable, scales = "free") +
  scale_color_manual(name = "Annual Averages", values = c("gray60","turquoise4", "darkgoldenrod3"), labels = (c("Historical", paste(model_bc, model_bc_rcp_name), paste(model_wc, model_wc_rcp_name)))) +
  theme(legend.text = element_text(size = 10),
        legend.title = element_text(size = 10)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 4))
  

ggsave(here::here(site, #site subfolder
                  "figures", #subfolder
                  paste("lat",lat,"lon",lon, sep = "_"),
                  "annual_facet.png")) #file name

```
## Individual Graphs of change over time

```{r, out.width="50%"}

wrap_sentence <- function(string, width) {
  words <- unlist(strsplit(string, " "))
  fullsentence <- ""
  checklen <- ""
  for(i in 1:length(words)) {
    checklen <- paste(checklen, words[i])
    if(nchar(checklen)>(width+1)) {
      fullsentence <- paste0(fullsentence, "\n")
      checklen <- ""
    }
    fullsentence <- paste(fullsentence, words[i])
  }
  fullsentence <- sub("^\\s", "", fullsentence)
  fullsentence <- gsub("\n ", "\n", fullsentence)
  return(fullsentence)
} # this code taken from https://stackoverflow.com/a/27734975/14061596

plot_annual = function(.y, .l) { 
  #.y = historical
  #.x = future 4.5
  #.z = future 8.5
  #.l = highlighted drought year
   
   point_low <- annual_values %>%
     filter(variable %in% c(.y)) %>% 
     filter(year %in% c(.l))
   
   line_low <- point_low$value
  
  annual_graph_bc <- ggplot() +
    geom_line(data = annual_values %>% 
                filter(averages %in% c("annual_avg", "annual_avg_bc")) %>% 
                filter(variable == .y), # filter data for historical and bc lines
              aes(x = year, 
                  y = value, 
                  color = averages),
              size = .75) +
    geom_hline(data = point_low, # draws a line at a dry year
               yintercept = line_low, 
               linetype = "dashed",
               color = "firebrick3") +
    geom_point(data = point_low, # highlights a dry year point
               aes(x = year, y = value),
               color = "firebrick3",
               alpha =  0.25,
               size = 4) +
  labs(title = paste("Annual Average of", .y),
       y = ifelse(.y == "agdd_daily", "Growing Degree Days (C)",
                    "Water (mm)")) +
      geom_text(data = point_low, # labels the line
              aes(x = 1973, 
                  y = value,
                  label = year, 
                  vjust = -0.35), # -0.x moves the text up above the line
              color = "firebrick3") +
    scale_color_manual(name = "", values = c("gray60","turquoise4"), labels = (c("Historical", paste(model_bc, model_bc_rcp_name)))) # colors is a named vector, see top of function
 
  
  ggsave(here::here(site, #site subfolder
                    "figures", #subfolder
                    paste("lat",lat,"lon",lon,sep = "_"),
                    paste(.y, "annual_graph_bc.png", sep = "_"))) #file name
  
  
  annual_graph_wc <- ggplot() +
    geom_line(data = annual_values %>% 
                filter(averages %in% c("annual_avg", "annual_avg_wc")) %>%
                filter(variable == .y), # filter data for historical and wc lines
              aes(x = year, 
                  y = value, 
                  color = averages),
              size = .75) +
    geom_hline(data = point_low, 
               yintercept = line_low, 
               linetype = "dashed",
               color = "firebrick3") +
    geom_point(data = point_low, # highlights a dry year point
               aes(x = year, y = value),
               color = "firebrick3",
               alpha =  0.25,
               size = 4) +
  labs(title = paste("Annual Average of",.y),
       y = ifelse(.y == "ADGG", "Growing Degree Days (C)",
                    "Water (mm)")) +
    geom_text(data = point_low,
              aes(x = 1973, 
                  y = value,
                  label = year, 
                  vjust = -0.35),
              color = "firebrick3") +
    scale_color_manual(name = "", values = c("gray60", "darkgoldenrod3"), labels = (c("Historical", paste(model_wc, model_wc_rcp_name)))) # colors is a named vector, see top of function
  
  
  ggsave(here::here(site, #site subfolder
                    "figures", #subfolder
                    paste("lat",lat,"lon",lon, sep = "_"),
                    paste(.y, "annual_graph_wc.png", sep = "_"))) #filename
  
  # return(annual_graph_bc)
  # return(annual_graph_wc) with these two it only prints the 4.5 graph
  
  print(annual_graph_bc)
  print(annual_graph_wc)
  
  }

plot_annual("Runoff", "2002")
#plot_annual("AGDD", "2002")
plot_annual("Accumulated SWE", "2002")
plot_annual("PET", "2002")
plot_annual("AET", "2002")
plot_annual("Deficit", "2002")
plot_annual("Rain", "2002")
plot_annual("Soil Water", "2002")


```

```{r}
# --------
# jitter under boxplot
# --------

# ---------
# jitter best case
# ---------

dodge <- position_dodge(width = 1)

ggplot(data =  month_join_bc %>%
         filter(!variable %in% c("agdd_daily", "pet_daily")),
       aes(x = decades, 
           y = value, 
           shape = NULL)) + #originally had "group = decade" here
                            # this caused the facet_wrap to include all variables on all facets
  geom_jitter(aes(colour = decades),
             size = .9,
             alpha = 0.25) + # dodge is a written code (see above)
  geom_boxplot(aes(x = decades, # internet had "mapping =" in front of
                   # aes, removed and nothing changed
                   y = value),
               alpha = 0.3,
               nudge = 0.025,
               outlier.shape = NA,#hides outliers
               #position = dodge, # has to match the other half
               fill = "grey60") +
  scale_color_manual(breaks = c("1980-2019", "2020-2059", "2060-2099"),
                     values = c("goldenrod2", "darkolivegreen3", "turquoise4")) +
  scale_fill_manual(breaks = c("1980-2019", "2020-2059", "2060-2099"),
                     values = c("goldenrod2", "darkolivegreen3", "turquoise4")) +
  labs(y = "Water(mm)",
       title = paste(model_bc, model_bc_rcp_name)) +
  facet_wrap(~variable, scales = "free")

ggsave(here::here(site, #site subfolder
                  "figures", #subfolder
                  paste("lat",lat,"lon",lon, sep = "_"),
                  paste("jitter_water_all_bc.png", sep = "_"))) # file name

# ----------
# Jitter worst case
# ----------


ggplot(data =  month_join_wc %>%
         filter(!variable %in% c("agdd_daily", "pet_daily")),
       aes(x = decades, 
           y = value, 
           shape = NULL)) + #originally had "group = decade" here
                            # this caused the facet_wrap to include all variables on all facets
  geom_jitter(aes(colour = decades),
             size = .9,
             alpha = 0.25) + # dodge is a written code (see above)
  geom_boxplot(aes(x = decades, # internet had "mapping =" in front of
                   # aes, removed and nothing changed
                   y = value),
               alpha = 0.3,
               nudge = 0.025,
               outlier.shape = NA,#hides outliers
               #position = dodge, # has to match the other half
               fill = "grey60") +
  scale_color_manual(breaks = c("1980-2019", "2020-2059", "2060-2099"),
                     values = c("goldenrod2", "darkolivegreen3", "turquoise4")) +
  scale_fill_manual(breaks = c("1980-2019", "2020-2059", "2060-2099"),
                     values = c("goldenrod2", "darkolivegreen3", "turquoise4")) +
  labs(y = "Water(mm)",
       title = paste(model_wc, model_wc_rcp_name)) +
  facet_wrap(~variable, scales = "free")

ggsave(here::here(site, #site subfolder
                  "figures", #subfolder
                  paste("lat",lat,"lon",lon, sep = "_"),
                  paste("jitter_water_all_wc.png", sep = "_"))) # file name
```

```{r, eval=FALSE}

#save this rmd as a file based on the site name in the site folder
rmarkdown::render(here:here("water_balance_graphs.Rmd"),  # file 2
                   output_file =  paste(site, ".html", sep=""), 
                   output_dir = here::here(site))
```


