---
title: "Monthly Water Balance Data"
author: "Janelle Christensen"
date: "7/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# -------------
# Attach packages
# -------------

library(data.table) 
library(here)
#library(plyr) 
# be careful with this, it causes issues for dplyr::group_by
# I didn't try, but the internet says if you load it before tidyverse, that issue goes away
library(tidyverse)
library(beepr)
library(lubridate)
library(directlabels)
library(data.table)
library(ggbeeswarm)
library(gghalves)
library(stringr)

# ------------
# set variables for the data
# ------------

site = "little_saddle_mtn" 

lat = 44.702 

lon = -110.018 

start = 1980 

end = 2019
```

```{r}
# -------------
# clean data for graphing
# -------------


site_df <- read_csv(here::here("raw_data", paste(site,"lat",lat,"lon",lon,"monthly_historical.csv", sep = "_"))) %>% 
  select(-lat, -lon) %>% 
  mutate(date_new = lubridate::ymd(paste(year,
                                     month, 
                                     sep = "-"),
                               truncated = 1)) %>% # truncated needs to be here, can't say why it's 1
  mutate(year = lubridate::year(date_new),
         month = lubridate::month(date_new, 
                                  label = TRUE, 
                                  abbr = TRUE))
```

# Graphs for comparing years

## 1980 and 2018

```{r, fig.show="hold", out.width="25%"}
# -------------
# I'd like to try a function
# 1980 2018 function
# -------------
plot_year = function(.y, .x, .z) {
  
  site_.x_.z <- site_df %>% 
    filter(year %in% c(.x, .z)) %>% 
    dplyr::group_by(year)
  
.x_.z_plot <- ggplot(site_.x_.z,
         aes(x = lubridate::month(date_new,
                                  label = TRUE,
                                  abbr = TRUE), 
             y = .data[[.y]],
             group = factor(year(date_new)),
             color = factor(lubridate::year(date_new)))) +
    geom_smooth(size = 1.1,
                se = FALSE) +
    theme_classic() +
    labs(color = "Year",
         y = ifelse(.y == "agdd_monthly", "Growing Degree Days (C)", "Water (mm)"), # R needs the "" here
         # the ifelse goes after the command you want to change
         #.y is useful because it prevents R from confusing it with something else
         # purrr is much more useful than a for loop here
         # if {} else{} and if_else() both didn't work, but I don't know why
         title = ifelse(.y ==  "soil_water_monthly", "Soil Water", 
                        ifelse(.y == "runoff_monthly",
                               "Runoff",
                               ifelse(.y == "rain_monthly", 
                                      "Rain",
                                      ifelse(
                                        .y == "agdd_monthly",
                                        "Accumlated Growing Degree Days",
                                        ifelse(
                                          .y == "accumswe_monthly",
                                          "Accumulated Snow Water Equvalent",
                                          ifelse(
                                            .y == "pet_monthly",
                                            "Predicted Evapotranspiration",
                                            ifelse(
                                              .y == "deficit_monthly",
                                              "Deficit",
                                              "Actual Evapotranspiration")))))))) +
         theme(panel.grid = element_blank(),
               plot.title = element_text(size = 25),
               legend.text = element_text(size = 15),
               legend.title = element_text(size = 18),
               axis.title.x = element_blank(),
               axis.title.y = element_text(size = 15),
               axis.text.x = element_text(size = 9),
               legend.position = "top")+
    scale_color_manual(breaks = c(.x, .z),
                       values = c("turquoise4", "darkolivegreen3"))

  ggsave(here::here("figures", #top folder in wd
                    paste(site,lat,lon, sep = ""), #subfolder of figures
                    "year", #sub folder of above
                    paste(.x,.z, sep = "_"), #sub folder of year
                    paste(site,lat,lon, .y, .x, .z, ".png", sep = ""))) #file name (r will do this)
  
  print(.x_.z_plot)
}


######
######
######


# BEFORE RUNNING THE FUNCTION
# make sure you have created the folders as necessary in your wd
# folders need to be wd (wherever you have put it) 
  # -> figures (written just like this)
    #-> paste(site,lat,lon, sep = "") (i.e. test_site45-111) 
      #-> year (written just like this)
        #->  paste(.x,.z, sep = "_") (i.e. 1988_2011)


######
######
######

# plot_year("runoff_monthly", "1980", "2018")
# plot_year("agdd_monthly", "1980", "2018")
# plot_year("soil_water_monthly", "1980", "2018")
# plot_year("rain_monthly", "1980", "2018")
# plot_year("accumswe_monthly", "1980", "2018")
# plot_year("pet_monthly", "1980", "2018")
# plot_year("deficit_monthly", "1980", "2018")
# plot_year("aet_monthly", "1980", "2018")

```

## 1988 and 2011

```{r, fig.show="hold", out.width="25%"}
plot_year("runoff_monthly", "1988", "2011")
plot_year("agdd_monthly", "1988", "2011")
plot_year("soil_water_monthly", "1988", "2011")
plot_year("rain_monthly", "1988", "2011")
plot_year("accumswe_monthly", "1988", "2011")
plot_year("pet_monthly", "1988", "2011")
plot_year("deficit_monthly", "1988", "2011")
plot_year("deficit_monthly", "1988", "2011")


```

# Graphs for comparing decades

## 1980s and 2010s

```{r, fig.show="hold", out.width="25%"}
# --------------
# tidy data to make graphs into decades
# --------------

site_1980s <- site_df %>% 
  dplyr::group_by(month) %>% 
  filter(year %in% c(1980:1989)) %>% 
  summarize(soil_water_monthly = mean(soil_water_monthly), #average by decade
            runoff_monthly = mean(runoff_monthly),
            rain_monthly = mean(rain_monthly),
            agdd_monthly = mean(agdd_monthly),
            accumswe_monthly = mean(accumswe_monthly),
            pet_monthly = mean(pet_monthly),
            deficit_monthly = mean(deficit_monthly),
            aet_monthly = mean(aet_monthly)) %>% 
  mutate(decade = "1980s")

site_1990s <- site_df %>% 
  dplyr::group_by(month) %>% 
  filter(year %in% c(1990:1999)) %>% 
  summarize(soil_water_monthly = mean(soil_water_monthly),
            runoff_monthly = mean(runoff_monthly),
            rain_monthly = mean(rain_monthly),
            agdd_monthly = mean(agdd_monthly),
            accumswe_monthly = mean(accumswe_monthly),
            pet_monthly = mean(pet_monthly),
            deficit_monthly = mean(deficit_monthly),
            aet_monthly = mean(aet_monthly)) %>% 
  mutate(decade = "1990s")

site_2000s <- site_df %>% 
  dplyr::group_by(month) %>% 
  filter(year %in% c(2000:2009)) %>% 
  summarize(soil_water_monthly = mean(soil_water_monthly),
            runoff_monthly = mean(runoff_monthly),
            rain_monthly = mean(rain_monthly),
            agdd_monthly = mean(agdd_monthly),
            accumswe_monthly = mean(accumswe_monthly),
            pet_monthly = mean(pet_monthly),
            deficit_monthly = mean(deficit_monthly),
            aet_monthly = mean(aet_monthly)) %>% 
  mutate(decade = "2000s")

site_2010s <- site_df %>% 
  dplyr::group_by(month) %>% 
  filter(year %in% c(2010:2018)) %>%
  summarize(soil_water_monthly = mean(soil_water_monthly),
            runoff_monthly = mean(runoff_monthly),
            rain_monthly = mean(rain_monthly),
            agdd_monthly = mean(agdd_monthly),
            accumswe_monthly = mean(accumswe_monthly),
            pet_monthly = mean(pet_monthly),
            deficit_monthly = mean(deficit_monthly),
            aet_monthly = mean(aet_monthly)) %>%
  mutate(decade = "2010s")

site_decade <- site_1980s %>% #recombine them into one df
  full_join(site_1990s) %>% 
  full_join(site_2000s) %>% 
  full_join(site_2010s) 

# ------------
# plot for 1980s and 2010s
# ------------

plot_decades = function(.y, .x, .z) {
  
  site_.x_.z <- site_decade %>% 
    filter(decade %in% c(.x, .z))
  
.x_.z_plot <-   ggplot(site_.x_.z,
         aes(x = month,
             group = decade,
             color = decade, 
             y = .data[[.y]]),#.y is a character vector, so need .data surrounding .y
         ) +
    geom_smooth(size = 1.1,
                se = FALSE) +
    theme_classic() +
    labs(x = "Month",
         color = "Year",
         y = ifelse(.y == "agdd_monthly", "Growing Degree Days (C)", "Water (mm)"), # R needs the "" here
         # the ifelse goes after the command you want to change
         #.y is useful because it prevents R from confusing it with something else
         # purrr is much more useful than a for loop here
         # if {} else{} and if_else() both didn't work, but I don't know why
         title = ifelse(.y ==  "soil_water_monthly", "Soil Water", 
                        ifelse(.y == "runoff_monthly",
                               "Runoff",
                               ifelse(.y == "rain_monthly", 
                                      "Rain",
                                      ifelse(
                                        .y == "agdd_monthly",
                                        "Accumlated Growing Degree Days",
                                        ifelse(
                                          .y == "accumswe_monthly",
                                          "Accumulated Snow Water Equvalent",
                                          ifelse(
                                            .y == "pet_monthly",
                                            "Predicted Evapotranspiration",
                                            ifelse(
                                              .y == "deficit_monthly",
                                              "Deficit",
                                              "Actual Evapotranspiration")))))))) +
    theme(panel.grid = element_blank(),
          plot.title = element_text(size = 25),
          legend.text = element_text(size = 15),
          legend.title = element_text(size = 18),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 15),
          axis.text.x = element_text(size = 9),
          legend.position = "top") +
    scale_color_manual(breaks = c(.x, .z),
                       values = c("turquoise4", "darkolivegreen3"))
  
  ggsave(here::here("figures", # top folder
                    paste(site,lat,lon, sep = ""), #sub folder
                    "decade", # sub folder
                    paste(.x, .z, sep = "_"), # sub folder
                    paste(site,lat,lon, .y, .x, .z , ".png", sep = ""))) # file name (r will do this)
  
  print(.x_.z_plot)
}

######
######
######


# BEFORE RUNNING THE FUNCTION
# make sure you have created the folders as necessary in your wd
# folders need to be:
# wd (wherever you have put it) 
  # -> figures (written just like this)
    # -> paste(site,lat,lon, sep = "") (i.e. test_site45-111) 
      # -> decade (written just like this)
        # ->  paste(.x,.z, sep = "_") (i.e. 1980s_2010s)


######
######
######


plot_decades("runoff_monthly", "1980s", "2010s")
plot_decades("agdd_monthly", "1980s", "2010s")
plot_decades("soil_water_monthly", "1980s", "2010s")
plot_decades("rain_monthly", "1980s", "2010s")
plot_decades("accumswe_monthly", "1980s", "2010s")
plot_decades("pet_monthly", "1980s", "2010s")
plot_decades("deficit_monthly", "1980s", "2010s")
plot_decades("aet_monthly", "1980s", "2010s")


```

# Graphs for comparing pre and post 2000s

```{r, fig.show="hold", out.width="25%"}

# -------------
# tidy data to be pre-post 2000s
# -------------


site_1980s_1990s <- site_df %>% 
  dplyr::group_by(month) %>% 
  filter(year %in% c(1980:1999)) %>%
  summarize(soil_water_monthly = mean(soil_water_monthly),
            runoff_monthly = mean(runoff_monthly),
            rain_monthly = mean(rain_monthly),
            agdd_monthly = mean(agdd_monthly),
            accumswe_monthly = mean(accumswe_monthly),
            pet_monthly = mean(pet_monthly),
            deficit_monthly = mean(deficit_monthly),
            aet_monthly = mean(aet_monthly)) %>%
  mutate(decade = "Pre 2000s")

site_2000s_2010s <- site_df %>% 
  dplyr::group_by(month) %>% 
  filter(year %in% c(2000:2018)) %>% 
  summarize(soil_water_monthly = mean(soil_water_monthly),
            runoff_monthly = mean(runoff_monthly),
            rain_monthly = mean(rain_monthly),
            agdd_monthly = mean(agdd_monthly),
            accumswe_monthly = mean(accumswe_monthly),
            pet_monthly = mean(pet_monthly),
            deficit_monthly = mean(deficit_monthly),
            aet_monthly = mean(aet_monthly)) %>% 
  mutate(decade = "Post 2000s")

site_pre_post_2000s <- site_1980s_1990s %>% 
  full_join(site_2000s_2010s)

# ------------
# plot for pre and post and 2000s
# ------------

plot_pre_post_2000s = function(.y) {
  .y_plot <- ggplot(site_pre_post_2000s,
         aes(x = month,
             group = decade,
             color = decade, 
             y = .data[[.y]])) + # calling my variable, which I'll name later in the command +
    geom_smooth(size = 1.1,
                se = FALSE) +
    theme_classic() +
    labs(x = "Month",
         color = "Year",
         y = ifelse(.y == "agdd_monthly", "Growing Degree Days (C)", "Water (mm)"), # R needs the "" here
         # the ifelse goes after the command you want to change
         #.y is useful because it prevents R from confusing it with something else
         # purrr is much more useful than a for loop here
         # if {} else{} and if_else() both didn't work, but I don't know why
         title = ifelse(.y ==  "soil_water_monthly", "Soil Water", #title based on variable
                        ifelse(.y == "runoff_monthly",
                               "Runoff",
                               ifelse(.y == "rain_monthly", 
                                      "Rain",
                                      ifelse(
                                        .y == "agdd_monthly",
                                        "Accumlated Growing Degree Days",
                                        ifelse(
                                          .y == "accumswe_monthly",
                                          "Accumulated Snow Water Equvalent",
                                          ifelse(
                                            .y == "pet_monthly",
                                            "Predicted Evapotranspiration",
                                            ifelse(
                                              .y == "deficit_monthly",
                                              "Deficit",
                                              "Actual Evapotranspiration")))))))) +
    theme(panel.grid = element_blank(), #removes grid lines
          plot.title = element_text(size = 25),
          legend.text = element_text(size = 15),
          legend.title = element_text(size = 18),
          axis.title.x = element_blank(), # removes x axis labs
          axis.title.y = element_text(size = 15),
          axis.text.x = element_text(size = 9),
          legend.position = "top") + 
    scale_color_manual(breaks = c("Pre 2000s", "Post 2000s"),
                       values = c("turquoise4", "darkolivegreen3"))
  
  ggsave(here::here("figures", #top folder
                    paste(site,lat,lon, sep = ""), #subfolder
                    "pre_post_2000s", # subfolder
                    paste(site,lat,lon, .y, "pre_post_2000s", ".png", sep = ""))) #file name
  
  print(.y_plot)
}



######
######
######


# BEFORE RUNNING THE FUNCTION
# make sure you have created the folders as necessary in your wd
# folders need to be:
# wd (wherever you have put it) 
#   -> figures (written just like this)
#     -> paste(site,lat,lon, sep = "") (i.e. test_site45-111) 
#       -> pre_post_2000s (written just like this)


######
######
######

plot_pre_post_2000s("runoff_monthly")
plot_pre_post_2000s("agdd_monthly")
plot_pre_post_2000s("soil_water_monthly")
plot_pre_post_2000s("rain_monthly")
plot_pre_post_2000s("accumswe_monthly")
plot_pre_post_2000s("pet_monthly")
plot_pre_post_2000s("deficit_monthly")
plot_pre_post_2000s("aet_monthly")

```


# Histograms to look at data spread

```{r}
# -------------
# Graph for plots of the data comparing all variables
# -------------

# created df for general data, maybe can be used later
site_long <- site_df %>% 
  pivot_longer(`soil_water_monthly`:`aet_monthly`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "value") %>% # new column name to store values
  mutate(variable = case_when(
    .$variable == "runoff_monthly" ~ "Runoff",
    #.Svariable calls the variable, then it can be renamed
    .$variable == "agdd_monthly" ~ "AGDD",
    .$variable == "soil_water_monthly" ~ "Soil Water",
    .$variable == "rain_monthly" ~ "Rain",
    .$variable == "accumswe_monthly" ~ "Accumulated SWE",
    .$variable == "pet_monthly" ~ "PET",
    .$variable == "deficit_monthly" ~ "Deficit",
    TRUE ~ "AET" # last ifelse is just labeled as TRUE
  )) %>% 
  mutate(decade = case_when(
    .$year %in% c(1980:1989) ~ "1980s",
    .$year %in% c(1990:1999) ~ "1990s",
    .$year %in% c(2000:2009) ~ "2000s",
    TRUE ~ "2010s"
  )) %>% 
  group_by(variable) 

water_site_long <- site_long %>% 
  filter(!variable %in% c("AGDD", "PET")) %>% 
  group_by(decade, variable) %>% 
  mutate(mean_value = mean(value),
         sd_value = sd(value),
         sample_size = n(),
         se_value = sd(value) / sqrt(n()),
         median_value = median(value))

# ------------
# explore the data with histograms
# should I be plotting means? Medians? 
# depends on skew, maybe I'll plot both
# ------------

site_long_1980s <- site_long %>% 
  filter(decade %in% c("1980s"))

site_long_1990s <- site_long %>% 
  filter(decade %in% c("1990s"))

site_long_2000s <- site_long %>% 
  filter(decade %in% c("2000s"))

site_long_2010s <- site_long %>% 
  filter(decade %in% c("2010s"))

ggplot(data = site_long) +
  geom_histogram(aes(x = value), binwidth = 10) +
  facet_wrap(~variable)

ggplot(data = site_long_1980s) +
  geom_histogram(aes(x = value), binwidth = 10) +
  facet_wrap(~variable)

ggplot(data = site_long_1990s) +
  geom_histogram(aes(x = value), binwidth = 10) +
  facet_wrap(~variable)

ggplot(data = site_long_2000s) +
  geom_histogram(aes(x = value), binwidth = 10) +
  facet_wrap(~variable)

ggplot(data = site_long_2010s) +
  geom_histogram(aes(x = value), binwidth = 10) +
  facet_wrap(~variable)

ggplot(data = site_long, aes(sample = value))+
  geom_qq() +
  facet_wrap(~variable)

ggplot(data = site_long_1980s, aes(sample = value))+
  geom_qq() +
  facet_wrap(~variable)

ggplot(data = site_long_1990s, aes(sample = value))+
  geom_qq() +
  facet_wrap(~variable)

ggplot(data = site_long_2000s, aes(sample = value))+
  geom_qq() +
  facet_wrap(~variable)

ggplot(data = site_long_2010s, aes(sample = value))+
  geom_qq() +
  facet_wrap(~variable)

# all data is skewed either positively or negatively
# to me this means that I should look at the median of this data
# will do both

```

# Graphs for bar and jitter plots

```{r}

# ----------
# grouped bar plot
# ----------

ggplot(data = water_site_long, 
       aes(x = variable, 
           y = mean_value, 
           shape = NULL,
           group = decade)) +
  geom_bar(stat = "identity", 
               width = 0.9, 
               position = position_dodge(0.9),
               #position = position_dodge(0.9) puts them next to each other
               #otherwise stacked
               #0.9 has something to do with where they are in relation to each other
               #0.5 had them overlapping
               # -0.9 is a hacky way of reversing the order of the bars due to coord_flip
               #stat = "identity" is necessary, but I couldn't find what else could go in there
               aes(color = decade,
                fill = decade)) +
  geom_errorbar(aes(x = variable,
                ymin = mean_value - se_value,
                ymax = mean_value + se_value),
                width = .3,
                position = position_dodge(.9)) +
  # -0.9 is a hacky way of reversing the order of the bars due to coord_flip
  theme_classic() +
  theme(panel.grid = element_blank(),
        plot.title = element_text(size = 25),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 18),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 15),
        axis.text = element_text(size = 11)) +
   scale_color_manual(breaks = c("1980s", "1990s", "2000s", "2010s"),
                      values = c("goldenrod2", "darkolivegreen3", "lemonchiffon4", "turquoise4")) +
   scale_fill_manual(breaks = c("1980s", "1990s", "2000s", "2010s"),
                     values = c("goldenrod2", "darkolivegreen3", "lemonchiffon4", "turquoise4")) +
   labs(y = "Water(mm)") +
  scale_x_discrete(labels = function(variable) str_wrap(variable, width = 10))

ggsave(here::here("figures", "test.png"))


```
# Jitter boxplot for the year

```{r}

# ---------
# jitter plot under box plot (displays medians)
# ---------

site_long_median <- site_long %>% # need separate median data because group_by(variable, decade) 
  #in the water_site_long was causing issues
  mutate(mean_value = mean(value),
         sd_value = sd(value),
         sample_size = n(),
         se_value = sd(value) / sqrt(n()),
         median_value = median(value)) %>% 
  filter(!variable %in% c("AGDD", "PET"))

dodge <- position_dodge(width = 1)

ggplot(data = site_long_median, 
       aes(x = factor(variable), 
           y = value, 
           shape = NULL)) + #originally had "group = decade" here
                            # this caused the facet_wrap to include all variables on all facets
  geom_half_point(aes(colour = decade),
             size = .9,
             alpha = 0.25,
             position = dodge) + # dodge is a written code (see above)
  geom_half_boxplot(data = site_long_median,
               aes(x = variable, # internet had "mapping =" in front of
                   # aes, removed and nothing changed
                   y = value,
                   fill = decade),
               alpha = 0.8,
               nudge = 0.025,
               outlier.shape = NA,#hides outliers
               position = dodge) + # has to match the other half
  theme_classic() +
  theme(panel.grid = element_blank(),
        plot.title = element_text(size = 25),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 18),
        axis.title.y = element_text(size = 10),
        axis.title.x = element_text(size = 10),
        axis.text.x = element_blank()) +
  scale_color_manual(breaks = c("1980s", "1990s", "2000s", "2010s"),
                     values = c("goldenrod2", "darkolivegreen3", "lemonchiffon4", "turquoise4")) +
  scale_fill_manual(breaks = c("1980s", "1990s", "2000s", "2010s"),
                    values = c("goldenrod2", "darkolivegreen3", "lemonchiffon4", "turquoise4")) +
  labs(y = "Water(mm)") +
  facet_wrap(~variable, scales = "free")

ggsave(here::here("figures", "jitter_water_all.png"))


```

# Jitter boxplot for months of May - September

```{r}

# -----------
# filter out rainy months only
# -----------

site_long_months <- site_long_median %>% #needed separate median data because the group_by was causing issues
  filter(month %in% c("May", "Jun", "Jul", "Aug", "Sep"))


ggplot(data = site_long_months, 
       aes(x = factor(variable), 
           y = value, 
           shape = NULL)) + #originally had "group = decade" here
                            # this caused weird stuff with facet_wrap
  geom_half_point(aes(colour = decade),
             #position = position_jitterdodge(dodge.width=1), #does jitter plot for these separate variables
             size = .9,
             alpha = 0.25,
             position = dodge) + # dodge is a written code (see above)
  geom_half_boxplot(data = site_long_months,
               aes(x = variable, # internet had "mapping =" in front of
                   # aes, removed and nothing changed
                   y = value,
                   fill = decade),
               alpha = 0.8,
               nudge = 0.025,
               outlier.shape = NA,#hides outliers
               position = dodge) + # has to match the other half
  theme_classic() +
  theme(panel.grid = element_blank(),
        plot.title = element_text(size = 25),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 18),
        axis.title.y = element_text(size = 10),
        axis.title.x = element_text(size = 10),
        axis.text.x = element_blank()) +
  scale_color_manual(breaks = c("1980s", "1990s", "2000s", "2010s"),
                     values = c("goldenrod2", "darkolivegreen3", "lemonchiffon4", "turquoise4")) +
  scale_fill_manual(breaks = c("1980s", "1990s", "2000s", "2010s"),
                    values = c("goldenrod2", "darkolivegreen3", "lemonchiffon4", "turquoise4")) +
  labs(y = "Water(mm)",
       x = "") +
  facet_wrap(~variable, scales = "free")

ggsave(here::here("figures", "jitter_water_rainy.png"))


```

# Histograms and qqplots of the data

```{r}

# ------------
# separate data by decades
# ------------

site_long_months_1980s <- site_long_months %>% 
  filter(decade %in% c("1980s"))

site_long_months_1990s <- site_long_months %>% 
  filter(decade %in% c("1990s"))

site_long_months_2000s <- site_long_months %>% 
  filter(decade %in% c("2000s"))

site_long_months_2010s <- site_long_months %>% 
  filter(decade %in% c("2010s"))

# ------------
# histograms and qq plots
# ------------

ggplot(data = site_long_months) +
  geom_histogram(aes(x = value), binwidth = 10) +
  facet_wrap(~variable) +
  labs(title = "All Decades")

ggplot(data = site_long_months_1980s) +
  geom_histogram(aes(x = value), binwidth = 10) +
  facet_wrap(~variable) +
  labs(title = "1980s")

ggplot(data = site_long_months_1990s) +
  geom_histogram(aes(x = value), binwidth = 10) +
  facet_wrap(~variable)+
  labs(title = "1990s")

ggplot(data = site_long_months_2000s) +
  geom_histogram(aes(x = value), binwidth = 10) +
  facet_wrap(~variable)+
  labs(title = "2000s")

ggplot(data = site_long_months_2010s) +
  geom_histogram(aes(x = value), binwidth = 10) +
  facet_wrap(~variable)+
  labs(title = "2010s")

ggplot(data = site_long_months, aes(sample = value))+
  geom_qq() +
  facet_wrap(~variable)+
  labs(title = "All Decades")

ggplot(data = site_long_months_1980s, aes(sample = value))+
  geom_qq() +
  facet_wrap(~variable)+
  labs(title = "1980s")

ggplot(data = site_long_months_1990s, aes(sample = value))+
  geom_qq() +
  facet_wrap(~variable)+
  labs(title = "1990s")

ggplot(data = site_long_months_2000s, aes(sample = value))+
  geom_qq() +
  facet_wrap(~variable)+
  labs(title = "2000s")

ggplot(data = site_long_months_2010s, aes(sample = value))+
  geom_qq() +
  facet_wrap(~variable)+
  labs(title = "2010s")


```



