---
title: "Future graphs"
author: "Janelle Christensen"
date: "7/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}

library(data.table) 
library(here)
#library(plyr) 
# be careful with this, it causes issues for dplyr::group_by
# I didn't try, but the internet says if you load it before tidyverse, that issue goes away
library(tidyverse)
library(beepr)
library(lubridate)
library(directlabels)
library(data.table)
library(ggbeeswarm)
library(gghalves)

# ------------
# set variables for the data
# ------------

site = "little_saddle_mtn" 

lat = 44.702

lon = -110.018

start = 2020 

end = 2099

model = "MRI-CGCM3"

# model options: CCSM4, inmcm4, NorESM1-M, MRI-CGCM3, MIROC5, IPSL-CM5A-LR,  HadGEM2-CC365, GFDL-ESM2G, CanESM2, CSIRO-Mk3-6-0, CNRM-CM5, BNU-ESM

```


```{r}
# ------------
# clean data for graphing
# ------------

site_df <- read_csv(here::here("raw_data", paste(site,"lat",lat,"lon",lon,model,"daily_future.csv", sep = "_")),
                    na = c("-3276.7"))

# ---------
# this is only for now
# won't mess up the code if not removed
# named codes wrong when downloading
# ---------

colnames(site_df)[]<-c("date", "lat","lon","soil_water_daily_85", "runoff_daily_85", "rain_daily_85", "agdd_daily_85", "accumswe_daily_85", "pet_daily_85", "deficit_daily_85", "aet_daily_85", "soil_water_daily_45", "runoff_daily_45", "rain_daily_45", "agdd_daily_45", "accumswe_daily_45", "pet_daily_45", "deficit_daily_45", "aet_daily_45") 

site_df <- site_df %>% 
  select(-lat, -lon)  %>% 
  mutate(year = lubridate::year(date), 
                month = lubridate::month(date,
                                         label = TRUE, 
                                         abbr = TRUE), 
                day = lubridate::day(date),
         doy = yday(date)) 


```


```{r}
# -------------
# Graph for plots of the data comparing all variables
# -------------

# created df for general data, maybe can be used later
site_long_85 <- site_df %>%
  select(date:aet_daily_85, year:doy) %>% 
  pivot_longer(`soil_water_daily_85`:`aet_daily_85`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "rcp_85") %>% 
  mutate(variable = case_when(
    .$variable == "runoff_daily_85" ~ "Runoff",
    #.Svariable calls the variable, then it can be renamed
    .$variable == "agdd_daily_85" ~ "AGDD",
    .$variable == "soil_water_daily_85" ~ "Soil Water",
    .$variable == "rain_daily_85" ~ "Rain",
    .$variable == "accumswe_daily_85" ~ "Accumulated SWE",
    .$variable == "pet_daily_85" ~ "PET",
    .$variable == "deficit_daily_85" ~ "Deficit",
    TRUE ~ "AET"))
  
  
site_long_45 <- site_df %>% 
  select(date, soil_water_daily_45:aet_daily_45, year:doy) %>% 
  pivot_longer(`soil_water_daily_45`:`aet_daily_45`, # The columns I'm gathering together
               names_to = "variable", # new column name for existing names
               values_to = "rcp_45") %>% 
  mutate(variable = case_when(
    .$variable == "runoff_daily_45" ~ "Runoff",
    #.Svariable calls the variable, then it can be renamed
    .$variable == "agdd_daily_45" ~ "AGDD",
    .$variable == "soil_water_daily_45" ~ "Soil Water",
    .$variable == "rain_daily_45" ~ "Rain",
    .$variable == "accumswe_daily_45" ~ "Accumulated SWE",
    .$variable == "pet_daily_45" ~ "PET",
    .$variable == "deficit_daily_45" ~ "Deficit",
    TRUE ~ "AET" # last ifelse is just labeled as TRUE
  ))

site_long <- site_long_45 %>%
  inner_join(site_long_85) %>%
  mutate(decade = case_when(
    .$year %in% c(2020:2029) ~ "2020s",
    .$year %in% c(2030:2039) ~ "2030s",
    .$year %in% c(2040:2049) ~ "2040s",
    .$year %in% c(2050:2059) ~ "2050s",
    .$year %in% c(2060:2069) ~ "2060s",
    .$year %in% c(2070:2079) ~ "2070s",
    .$year %in% c(2080:2089) ~ "2080s",
    TRUE ~ "2090s"
  )) 


```


```{r}

# -------------
# I'd like to try a function
# 1980 2018 function
# -------------


plot_year = function(.y, .x, .z) {
  
  site_.x_.z <- site_df %>% 
    filter(year %in% c(.x, .z)) %>% 
    dplyr::group_by(year)
  
.x_.z_plot <- ggplot(site_.x_.z) +
  geom_smooth(aes(x = doy,
                  y = .data[[.y]],
                  group = factor(lubridate::year(date)),
             color = factor(lubridate::year(date))),
             size = .9,
             se = FALSE) +
  theme_classic() +
  labs(color = "Year",
         y = ifelse(.y == "agdd_daily_85", "Growing Degree Days (C)",
                    "Water (mm)"), # R needs the "" here
         # the ifelse goes after the command you want to change
         #.y is useful because it prevents R from confusing it with something else
         # purrr is much more useful than a for loop here
         title = case_when(
           .y == "runoff_daily_45" ~ "Runoff RCP 4.5",
            #.Svariable calls the variable, then it can be renamed
           .y == "agdd_daily_45" ~ "Accumulated Growing Degree Days RCP 4.5",
           .y == "soil_water_daily_45" ~ "Soil Water RCP 4.5",
           .y == "rain_daily_45" ~ "Rain RCP 4.5",
           .y == "accumswe_daily_45" ~ "Accumulated SWE RCP 4.5",
           .y == "pet_daily_45" ~ "Potential Evapotranspiration RCP 4.5",
           .y == "deficit_daily_45" ~ "Deficit RCP 4.5",
           .y == "aet_daily_45" ~ "Actual Evapotranspiration RCP 4.5",
           .y == "runoff_daily_85" ~ "Runoff RCP 8.5",
            #site_.x_.zSvariable calls the variable, then it can be renamed
           .y == "agdd_daily_85" ~ "Accumulated Growing Degree Days RCP 8.5",
           .y == "soil_water_daily_85" ~ "Soil Water RCP 8.5",
           .y == "rain_daily_85" ~ "Rain RCP 8.5",
           .y == "accumswe_daily_85" ~ "Accumulated SWE RCP 8.5",
           .y == "pet_daily_85" ~ "Potential Evapotranspiration RCP 8.5",
           .y == "deficit_daily_85" ~ "Deficit RCP 8.5",
           TRUE ~ "Actual Evapotranspiration RCP 8.5")) +
         theme(panel.grid = element_blank(),
               plot.title = element_text(size = 25),
               legend.text = element_text(size = 15),
               legend.title = element_text(size = 18),
               axis.title.x = element_blank(),
               axis.title.y = element_text(size = 15),
               axis.text.x = element_text(size = 9),
               legend.position = "top")+
    scale_color_manual(breaks = c(.x, .z),
                       values = c("turquoise4", "darkolivegreen3"))

  ggsave(here::here("figures", #top folder in wd
                    paste(site,lat,lon, sep = ""), #subfolder of figures
                    "year", #sub folder of above
                    paste(.x,.z, sep = "_"), #sub folder of year
                    paste(site,lat,lon, .y, .x, .z, ".png", sep = ""))) #file name (r will do this)
  
  print(.x_.z_plot)
}


######
######
######


# BEFORE RUNNING THE FUNCTION
# make sure you have created the folders as necessary in your wd
# folders need to be wd (wherever you have put it) 
  # -> figures (written just like this) # subfolder of wd
    #-> paste(site,lat,lon, sep = "") (i.e. little_saddle_mtn44.702-110.018) # subfolder of figures
      #-> year (written just like this) # subfolder of test_site45-111
        #->  paste(.x,.z, sep = "_") (i.e. 1988_2011) # subfolder of year


######
######
######

# plot_year("runoff_daily", "1980", "2018")
# plot_year("agdd_daily", "1980", "2018")
# plot_year("soil_water_daily", "1980", "2018")
# plot_year("rain_daily", "1980", "2018")
# plot_year("accumswe_daily", "1980", "2018")
# plot_year("pet_daily", "1980", "2018")
# plot_year("deficit_daily", "1980", "2018")
# plot_year("deficit_daily", "1980", "2018")

```

## 1988 and 2011

```{r, fig.show="hold", out.width="25%"}
plot_year("runoff_daily_85", "2020", "2099")
plot_year("runoff_daily_45", "2020", "2099")
plot_year("agdd_daily_85", "2020", "2099")
plot_year("agdd_daily_45", "2020", "2099")
plot_year("soil_water_daily_85", "2020", "2099")
plot_year("soil_water_daily_45", "2020", "2099")
plot_year("rain_daily_85", "2020", "2099")
plot_year("rain_daily_45", "2020", "2099")
plot_year("accumswe_daily_85", "2020", "2099")
plot_year("accumswe_daily_45", "2020", "2099")
plot_year("pet_daily_85", "2020", "2099")
plot_year("pet_daily_45", "2020", "2099")
plot_year("deficit_daily_85", "2020", "2099")
plot_year("deficit_daily_45", "2020", "2099")
plot_year("aet_daily_85", "2020", "2099")
plot_year("aet_daily_45", "2020", "2099")

```


# Histograms to look at data spread



```{r} 

# if don't want in report, add include = FALSE inside {r}


# ------------
# explore the data with histograms
# should I be plotting means? Medians? 
# depends on skew, maybe I'll plot both
# ------------

plot_histogram = function(.y) {
  
  site_long_.y <- site_long %>%
    filter(decade %in% (.y))
  
.y_hist_45 <- ggplot(data = site_long_.y) +
    geom_histogram(aes(x = rcp_45), binwidth = 10) +
    facet_wrap(~variable)+
    labs(title = .y)

.y_hist_85 <- ggplot(data = site_long_.y) +
    geom_histogram(aes(x = rcp_85), binwidth = 10) +
    facet_wrap(~variable)+
    labs(title = .y)
  
  print(.y_hist_45)
  print(.y_hist_85)
}

plot_histogram("2020s")
plot_histogram("2030s")
plot_histogram("2040s")
plot_histogram("2050s")
plot_histogram("2060s")
plot_histogram("2070s")
plot_histogram("2080s")
plot_histogram("2090s")



# all data is skewed either positively or negatively
# to me this means that I should look at the median of this data
# will do both
# look at data removing months that aren't rainy

plot_rainy_histogram = function(.y) {
  
  site_long_.y <- site_long %>%
    filter(decade %in% (.y),
           month %in% c("May", "Jun", "Jul", "Aug", "Sep"))
  
.y_hist_45 <- ggplot(data = site_long_.y) +
    geom_histogram(aes(x = rcp_45), binwidth = 10) +
    facet_wrap(~variable)+
    labs(title = paste(.y, "May - Sep"))

.y_hist_85 <- ggplot(data = site_long_.y) +
    geom_histogram(aes(x = rcp_85), binwidth = 10) +
    facet_wrap(~variable)+
    labs(title = paste(.y, "May - Sep"))
  
  print(.y_hist_45)
  print(.y_hist_85)
}

plot_rainy_histogram("2020s")
plot_rainy_histogram("2030s")
plot_rainy_histogram("2040s")
plot_rainy_histogram("2050s")
plot_rainy_histogram("2060s")
plot_rainy_histogram("2070s")
plot_rainy_histogram("2080s")
plot_rainy_histogram("2090s")

# ---------
# qq plots of the data to look at data normalcy
# does it follow expected values?
# ---------

plot_qq = function(.y) {
  
  site_long_.y <- site_long %>%
    filter(decade %in% (.y))
  
.y_hist_45 <- ggplot(data = site_long_.y) +
    geom_qq(aes(sample = rcp_45)) +
    facet_wrap(~variable)+
    labs(title = .y)

.y_hist_85 <- ggplot(data = site_long_.y) +
    geom_qq(aes(sample = rcp_85)) +
    facet_wrap(~variable)+
    labs(title = .y)
  
  print(.y_hist_45)
  print(.y_hist_85)
}

plot_qq("2020s")
plot_qq("2030s")
plot_qq("2040s")
plot_qq("2050s")
plot_qq("2060s")
plot_qq("2070s")
plot_qq("2080s")
plot_qq("2090s")

plot_rainy_qq = function(.y) {
  
  site_long_.y <- site_long %>%
    filter(decade %in% (.y),
           month %in% c("May", "Jun", "Jul", "Aug", "Sep"))
  
.y_hist_45 <- ggplot(data = site_long_.y) +
    geom_qq(aes(sample = rcp_45)) +
    facet_wrap(~variable)+
    labs(title = paste(.y, "May - Sep"))

.y_hist_85 <- ggplot(data = site_long_.y) +
    geom_qq(aes(sample = rcp_85)) +
    facet_wrap(~variable)+
    labs(title = paste(.y, "May - Sep"))
  
  print(.y_hist_45)
  print(.y_hist_85)
}

plot_rainy_qq("2020s")
plot_rainy_qq("2030s")
plot_rainy_qq("2040s")
plot_rainy_qq("2050s")
plot_rainy_qq("2060s")
plot_rainy_qq("2070s")
plot_rainy_qq("2080s")
plot_rainy_qq("2090s")



```

# Graphs for bar and jitter plots

```{r}

# ----------
# grouped bar plot
# ----------

# graph of all decades is cluttered - change them to 30 yr chunks

water_long_decades <- site_long %>% 
  mutate(decades = case_when(
    .$year %in% c(2020:2049) ~ "2020s_2040s",
    .$year %in% c(2050:2079) ~ "2050s_2070s",
    TRUE ~ "2080s_2090s"
  ))%>% 
  filter(!variable %in% c("AGDD", "PET")) %>% #!variable filters out this data
  group_by(decades, variable) %>% 
  mutate(mean_value_85 = mean(rcp_85, na.rm = TRUE),
         sd_value_85 = sd(rcp_85, na.rm = TRUE),
         sample_size_85 = n(),
         se_value_85 = sd(rcp_85, na.rm = TRUE) / sqrt(n()),
         median_value_85 = median(rcp_85, na.rm = TRUE)) %>% 
  mutate(mean_value_45 = mean(rcp_45, na.rm = TRUE),
         sd_value_45 = sd(rcp_45, na.rm = TRUE),
         sample_size_45 = n(),
         se_value_45 = sd(rcp_45, na.rm = TRUE) / sqrt(n()),
         median_value_45 = median(rcp_45, na.rm = TRUE))

ggplot(data = water_long_decades, 
       aes(x = variable, 
           y = mean_value_85, 
           shape = NULL,
           group = decades)) +
  geom_bar(stat = "identity", 
               width = 0.7, 
               position = position_dodge(0.9),
               #position = position_dodge(0.9) puts them next to each other
               #otherwise stacked
               #0.9 has something to do with where they are in relation to each other
               #0.5 had them overlapping
               # -0.9 is a hacky way of reversing the order of the bars due to coord_flip
               #stat = "identity" is necessary, but I couldn't find what else could go in there
               aes(color = decades,
                fill = decades)) +
  geom_errorbar(aes(x = variable,
                ymin = mean_value_85 - se_value_85,
                ymax = mean_value_85 + se_value_85),
                width = .3,
                position = position_dodge(.9)) +
  # -0.9 is a hacky way of reversing the order of the bars due to coord_flip
  theme_classic() +
  theme(panel.grid = element_blank(),
        plot.title = element_text(size = 25),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 18),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 15),
        axis.text = element_text(size = 11)) +
   scale_color_manual(breaks = c("2020s_2040s", "2050s_2070s", "2080s_2090s"),
                      values = c("goldenrod2", "darkolivegreen3", "turquoise4")) +
   scale_fill_manual(breaks = c("2020s_2040s", "2050s_2070s", "2080s_2090s"),
                     values = c("goldenrod2", "darkolivegreen3", "turquoise4")) +
   labs(y = "Water(mm)") +
  scale_x_discrete(labels = function(variable) str_wrap(variable, width = 10))

ggsave(here::here("figures", paste("bar",site,lat,lon,".png", sep = "")))


```


```{r}

# looks like the large number of zero values skews the data towards zero
# make averages by month and plot again

site_month_df <- site_long %>% 
  group_by(month, decade, variable) %>% 
  mutate(mean_45 = mean(rcp_45, na.rm = TRUE),
         mean_85 = mean(rcp_85, na.rm = TRUE))

```

```{r}

ggplot(data = site_month_df) +
  geom_point(aes(x = month, y = mean_45))

```


# Jitter boxplot for the year

```{r}

# ---------
# jitter plot under box plot (displays medians)
# ---------

site_long_median <- site_long %>% # need separate median data because group_by(variable, decade) 
  #in the water_site_long was causing issues
  mutate(mean_value = mean(value),
         sd_value = sd(value),
         sample_size = n(),
         se_value = sd(value) / sqrt(n()),
         median_value = median(value)) %>% 
  filter(!variable %in% c("AGDD", "PET"))

dodge <- position_dodge(width = 1)

ggplot(data = site_long_median, 
       aes(x = factor(variable), 
           y = value, 
           shape = NULL)) + #originally had "group = decade" here
                            # this caused the facet_wrap to include all variables on all facets
  geom_half_point(aes(colour = decade),
             size = .9,
             alpha = 0.25,
             position = dodge) + # dodge is a written code (see above)
  geom_half_boxplot(data = site_long_median,
               aes(x = variable, # internet had "mapping =" in front of
                   # aes, removed and nothing changed
                   y = value,
                   fill = decade),
               alpha = 0.8,
               nudge = 0.025,
               outlier.shape = NA,#hides outliers
               position = dodge) + # has to match the other half
  theme_classic() +
  theme(panel.grid = element_blank(),
        plot.title = element_text(size = 25),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 18),
        axis.title.y = element_text(size = 10),
        axis.title.x = element_text(size = 10),
        axis.text.x = element_blank()) +
  scale_color_manual(breaks = c("1980s", "1990s", "2000s", "2010s"),
                     values = c("goldenrod2", "darkolivegreen3", "lemonchiffon4", "turquoise4")) +
  scale_fill_manual(breaks = c("1980s", "1990s", "2000s", "2010s"),
                    values = c("goldenrod2", "darkolivegreen3", "lemonchiffon4", "turquoise4")) +
  labs(y = "Water(mm)") +
  facet_wrap(~variable, scales = "free")

ggsave(here::here("figures", "jitter_water_all.png"))


```

# Jitter boxplot for months of May - September

```{r}

# -----------
# filter out rainy months only
# -----------

site_long_months <- site_long_median %>% #needed separate median data because the group_by was causing issues
  filter(month %in% c("May", "Jun", "Jul", "Aug", "Sep"))


ggplot(data = site_long_months, 
       aes(x = factor(variable), 
           y = value, 
           shape = NULL)) + #originally had "group = decade" here
                            # this caused weird stuff with facet_wrap
  geom_half_point(aes(colour = decade),
             #position = position_jitterdodge(dodge.width=1), #does jitter plot for these separate variables
             size = .9,
             alpha = 0.25,
             position = dodge) + # dodge is a written code (see above)
  geom_half_boxplot(data = site_long_months,
               aes(x = variable, # internet had "mapping =" in front of
                   # aes, removed and nothing changed
                   y = value,
                   fill = decade),
               alpha = 0.8,
               nudge = 0.025,
               outlier.shape = NA,#hides outliers
               position = dodge) + # has to match the other half
  theme_classic() +
  theme(panel.grid = element_blank(),
        plot.title = element_text(size = 25),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 18),
        axis.title.y = element_text(size = 10),
        axis.title.x = element_text(size = 10),
        axis.text.x = element_blank()) +
  scale_color_manual(breaks = c("1980s", "1990s", "2000s", "2010s"),
                     values = c("goldenrod2", "darkolivegreen3", "lemonchiffon4", "turquoise4")) +
  scale_fill_manual(breaks = c("1980s", "1990s", "2000s", "2010s"),
                    values = c("goldenrod2", "darkolivegreen3", "lemonchiffon4", "turquoise4")) +
  labs(y = "Water(mm)",
       x = "") +
  facet_wrap(~variable, scales = "free")

ggsave(here::here("figures", "jitter_water_rainy.png"))


```
